### ISSUE TITLE
Strange property/comment behaviour

### ISSUE THREAD

**Issue by Markus-St** [pboettch/json-schema-validator#100]
Hi.
I found a very strange behaviour that occurs based on property names and comments. It occured in a very big and complicated schema, but I could reduce it to a very simple example. All tests have been done on the fix-96 branch, since you fixed an earlier problem on there for me.

So I am validating this JSON file:
```
{  
    "Prop1": 1,
    "Prop2": []
}
```
through this schema:
```
{
    "$id": "http://xxx.local/schemas/mySchema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",

    "type": "object",
    "properties": {
        "Prop1": {
            "type": "integer",
            "$comment": "Just a comment"
        },
        "Prop2": {
            "$ref": "#random_ref"
        }
    }
}
```
It validates fine, even though I should get an error on #random_ref, which is not defined. #97 would be a cause, that it's not found on `set_root_schema()`. But it should be found at least when validating, since he can't check if Prop2 is correct.

The verry strange thing is, that if I remove that comment **and/or** change the name of 'Prop1' to 'prop1' in the schema and json, I do get the correct error. Both, comments and upper/lowercase naming should not have any influence on the schema and it's validity.

Also, even if there is a `#random_ref` defined, the content of it does not get validated, which means Prop2 items can be whatever they want. This is breaking my real use "big" schema so far, that only the upper most level gets validated at all.

**Comment by pboettch** [comment]
I will but most likely the schema of Prop2 is seen an empty schema which is the same as a `true`-boolean schema: value is always valid.

**Comment by pboettch** [comment]
No, it was not what I was saying. The fix is in the same area as you report in your other issue.

**Comment by Markus-St** [comment]
A few things.
1. A property with a reference is not (or at least should not be) an empty Schema. It's a legal use, like described here: [Using id with ref](https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref).
2. As I pointed out, even if #random_ref is defined, it is not used to validate the property. So if Prop2 had something like `"$ref": "#prop2_settings"` and `#prop2_settings` is another object. You validator will not check if the 'Prop2' is an item that corresponds to `#prop2_settings` schema.
3. However it interprets it, there should be no difference if the comment is there or not and also no difference if the name is upper or lower case.
From json-schema.org reagrding to $comment elements: "JSON schema implementations aren’t allowed to attach any meaning or behavior to it whatsoever, and may even strip them at any time".

**Comment by pboettch** [comment]
The comment had nothing to do with. Could have been removed from the schema. In fact this validator is ignoring the $comment-field.

I cannot confirm your second point: fix the fix I made I get:

```
ERROR: '"/Prop2"' - '[]': unresolved schema-reference http://xxx.local/schemas/mySchema.json # random_ref
schema validation failed
```

When adding a `"$id": "#randomRef"` to Prop1 I get
```
ERROR: '"/Prop2"' - '[]': unexpected instance type
```

This is expected because Prop1 required type=int.
