### ISSUE TITLE
"required" field inside "properties" causes Segmentation Fault.

### ISSUE THREAD

**Issue by Markus-St** [pboettch/json-schema-validator#101]
Hi.
I accidentally did put the "required" field inside the "properties" field of an object. Although I know, this is not a correct schema, I think it should not crash. But it caused a Segmentation Fault on `validate()`.
Here is an exmaple:
```
{
    "$id": "http://xxx.local/schemas/mySchema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    
    "type": "object",
    "properties": {
        "top": {
            "type": "integer"
        },
	"required": ["value"]
    }
}
```

**Comment by pboettch** [comment]
I stumbled upon this very same bug last week, but hadn't realized this was the cause.

The problem here is that the value of the properties `required` has to be seen as a schema. And an array is not a valid schema. This should be an error and not a crash.
