### ISSUE TITLE
Memory leak with recursive schema

### ISSUE THREAD

**Issue by EShirykalov** [pboettch/json-schema-validator#109]
I defined very simple recursive schema:
```
{
    "$id": "test",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "definitions": {
        "item": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "next": { "$ref": "#/definitions/item" }
            },
            "required": [ "name" ]
        }
    },
    "properties": {
        "start": { "$ref": "#/definitions/item" }
    }
}
```
and validated this simple document using standard json-schema-validate application:
```
{
    "start": {
        "name": "1st",
        "next": {
            "name": "2nd"
        }
    }
}
```
Attached file contains valgrind report about memory leak.
I use commit 2cc7e9a.
GCC version:
`g++ (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)`

[valgrind.report.txt](https://github.com/pboettch/json-schema-validator/files/4562394/valgrind.report.txt)

**Comment by pboettch** [comment]
Every allocation in the validation is done within shared_ptr. It is astonishing that the are still non-freed references at the end of the program. I don't really know, what to do.

**Comment by pboettch** [comment]
I can reproduce it with this schema (and not validating anything):

```JSON
{
    "definitions": {
        "item": {
            "properties": {
                "next": { "$ref": "#/definitions/item" }
            }
        }
    }
}
```

It is related to the recursive next-link.

**Comment by pboettch** [comment]
I understood the problem, it is a circular dependency of `shared_ptr<>` to itself (indirectly via `schema_ref`).

Apparently this is where `weak_ptr<>` is useful. schema_ref now uses this and the orignal shared_ptr is only stored in the central schema-file.
Valgrind is not complaing anymore.
