### ISSUE TITLE
create a new tag for conda-forge

### ISSUE THREAD

**Issue by linus-gates** [pboettch/json-schema-validator#110]
I've been using this library for a while however I came across an error that have been fixed since 2.0.0, I need `cmake` to install `Config.cmake` file.
I use a specific *tag* not master since I use `conda`.
Could you create a new tag with all of the bug fixes so I could create a new & improved `conda` package?

Here is a link to the way the `conda` package is created: [json-schema-validator feedstock](https://github.com/conda-forge/json_schema_validator-feedstock/)

**Comment by pboettch** [comment]
Related to #80

**Comment by linus-gates** [comment]
Well updating the version in the `CMakeLists.txt` is fine, however I also need a tag since `conda` works with specific versions, not branches.
I would do it myself but I don't have any write permission to your repository and I can't push a tag by myself and github PR's won't add tags, only commits.

**Comment by pboettch** [comment]
The tag is supposed to made today. The CMakeLists.txt has changed months ago.

Giving out write permission generously is something I won't do - as long as I have the time to maintain.

However, feel free to insist if something does not go fast enough.
