### ISSUE TITLE
Empty conda package for windows

### ISSUE THREAD

**Issue by adriendelsalle** [pboettch/json-schema-validator#112]
Hi!

I tried to use your lib with conda package for Windows which seems to be empty.
I opened an issue on the [conda-forge feedstock](https://github.com/conda-forge/json_schema_validator-feedstock/issues/1) but no one had a look since.

Could you please tell me if you also maintain the conda feedstock?
Any hint to make it work?

Thanks!

**Comment by pboettch** [comment]
I don't know conda, but maybe @linus-gates and #110 can help?

**Comment by pboettch** [comment]
With the tag 2.1.0 made this week, did it improve the situation on conda's side?

**Comment by linus-gates** [comment]
No, what's wrong with the conda package for windows is that there isn't any `bld.bat` file which describes how to compile it to windows (there is `build.sh` for linux)

**Comment by pboettch** [comment]
What can we do in the repository?

**Comment by adriendelsalle** [comment]
Hi @pboettch @linus-gates 
I confirmed the windows package is still empty. As mentioned by @linus-gates and my issue on the feedstock, the windows recipe is missing.

To fix that we need to ask the current feedstock maintainer(s) to become maintainer and push a fix, or maybe only make a PR on that. I'm not used to that. @fcollonval, you already made this, could you please describe what are the options here? Thanks!

**Comment by pboettch** [comment]
I happily accept a pull-request.

**Comment by adriendelsalle** [comment]
This is on the conda forge feedstock repo that the modification has to be made 😅

**Comment by pboettch** [comment]
Then, I'm closing this one for now.

**Comment by adriendelsalle** [comment]
@pboettch FYI I finally finished that PR this morning (sorry I left it in progress for a while!).
https://github.com/conda-forge/json_schema_validator-feedstock/pull/4

It adds recipes for both win and osx.
