### ISSUE TITLE
Question about draft7/optional date-time

### ISSUE THREAD

**Issue by manuelgavidia** [pboettch/json-schema-validator#118]
Hello, first thanks for this library  ... one question: is this implementation complete for date-time format? I found some tests in the code that lead me assume that works, but not with the schema and json below. I am using tag 2.1.0.

```JSON
{
    "$defs": {
        "schema_info": {
            "type": "object",
            "properties": {
                "schema_model":   { "const" : "ACME" },
                "schema_version": { "const" : 1 }
             },
             "required": ["schema_model", "schema_version"]
        }
    },
    "type": "object",
    "properties": {
        "msg": {
            "type": "object",
            "properties": {
                "schema" : { "$ref": "#/$defs/schema_info" }
            },
            "required": ["schema"],
            "oneOf": [
                {
                    "properties": {
                        "pkt": { "const" : "OTHER" },
                        "name": { "type": "string"},
                        "time": { "type": "string", "format": "date-time" }
                     },
                    "required": ["pkt", "name", "time"]
                },
                {
                    "properties": {
                        "pkt": { "const" : "THISONE" },
                        "info": { "type": "string"},
                        "time": { "type": "string", "format": "date-time" }
                     },
                    "required": ["pkt", "info"]
                }
            ]
        }
    },
    "required": ["msg"]
}
```

```JSON
{
  "msg": {
    "info": "SOME MESSAGE",
    "pkt": "THISONE",
    "schema": {
      "schema_model": "ACME",
      "schema_version": 1
    },
    "time": "2020-06-05T00:04:06"
  }
}
```

The key "time" is not mandatory in the sub-schema (THISONE), but removing from schema validates goog_json. This schema is extracted from a bigger/complex one, but It shows the error. This schema + json validates in https://www.jsonschemavalidator.net/.

**Comment by pboettch** [comment]
Inheritance between logic-combination-schemas and base-properties is not supported by draft7 and thus by this validator.

You cannot mix `msg.properties` and `msg.oneOf` within a (sub-)schema. It won't work as expected : the oneOf-sub-schemas are not aware of the property `schema`.

Having said that, when not using `additonalProperties` (default true), your schema should work. Let me see.

**Comment by pboettch** [comment]
I locally add sub-schema-error output and see that

```
71:    sub-schema 1 did not validate: At /msg/time of "2020-06-05T00:04:06" - format-checking failed: 2020-06-05T00:04:06 is not a date-time string according to RFC 3339.
```

**Comment by pboettch** [comment]
According to RFC 3339 your date-time is missing a timezone or a `Z` at the end to indicate UTC.

**Comment by manuelgavidia** [comment]
@pboettch , thank you for the quick answer ... You are right about the "Z", but adding a "Z" as suffix to time string did not work for me - just checked. I also tried this value [date-time.json#L8](https://github.com/pboettch/json-schema-validator/blob/80333cda2bdae59edd4731bc7b2a91db3ef4e635/test/JSON-Schema-Test-Suite/tests/draft7/optional/format/date-time.json#L8), but didn't worked.

But as you said in https://github.com/pboettch/json-schema-validator/issues/118#issuecomment-639483971 , I should not use the "Inheritance between logic-combination-schemas and base-properties". OK !!!

Could you please show me where to insert the sub-schema error output of https://github.com/pboettch/json-schema-validator/issues/118#issuecomment-639507216 ?
