### ISSUE TITLE
Minimum condition error

### ISSUE THREAD

**Issue by SimonEbner** [pboettch/json-schema-validator#12]
Trying to validate the following json
```json
{
  "x": 1503681668603
}
```
with the following schema
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "x": {
      "type": "integer",
      "minimum": 1000000000000,
      "maximum": 2000000000000
    }
  }
}
```
fails validation with the following exception message
```
root.x exceeds minimum of 1000000000000.000000
```

Reducing the magnitude of the numbers to 

```json
{
  "x": 15
}
```
and
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "x": {
      "type": "integer",
      "minimum": 10,
      "maximum": 20
    }
  }
}
```
results in a successful validation. Possibly an overflow issue?

**Comment by pboettch** [comment]
Thanks for reporting. Yeah, it seems big numbers are not supported by this library. I already noticed it when passing the optional json-schema-tests 'bignum'.

**Comment by pboettch** [comment]
Actually, it is not really a bug - as json-schema is not requiring bigint support. There is already a problem with URIs which I cannot really solve without using a third-party-library. It seems the same is true here.

**Comment by pboettch** [comment]
Commit a5521b4b028f7ffd0aeafb221a3cc7ca0457aa51 extends the range by always using doubles for numeric values.
