### ISSUE TITLE
can this library support python

### ISSUE THREAD

**Issue by wangwei1237** [pboettch/json-schema-validator#120]
I am using python, and want to use this library for check the json validator. Can this library support python in the future? 

I try to use  the boost::python to wrap the library, but failed.

**Comment by pboettch** [comment]
For validation json using json-schema there is https://pypi.org/project/jsonschema/ which I'm using successfully in another project.

I think it makes little sense to add a python wrapper here. 

This project is bound to nlohmann::json which is a C++-library.

Is there a nlohmann::json-python-wrapper?

**Comment by wangwei1237** [comment]
I used this library in my c++ project, and in my python project, I want to use the same library. 

After I think about the python wrapper, I also think it makes little sense to add a python wrapper here.  

Because this library support shared library, I can use this shared library to wrap a python library with a little code. And it's OK now. 

Thank U.

**Comment by pboettch** [comment]
Feel free to share what you did to wrap it to python. Maybe it can help others in the future?

**Comment by wangwei1237** [comment]
I wrap this library to python as following step:
1. Building as shared library `libnlohmann_json_schema_validator.dylib`
2. Install the boost::python library: `brew install boost-python3`
3. Wrapping the library: 
```
// jsv_python.cpp

#include <iomanip>
#include <iostream>

#include <nlohmann/json-schema.hpp>
#include <boost/python.hpp>

using namespace boost::python;

class JSON_SCHEMA_VALIDATOR_API json_validator_python
{
private:
    nlohmann::json_schema::json_validator validator;

public:
    json_validator_python() {}
    void set_root_schema(const std::string &json_string) 
    {
        validator.set_root_schema(nlohmann::json::parse(json_string.begin(), json_string.end()));
    }

    void validate(const std::string &json_string) const
    {
        validator.validate(nlohmann::json::parse(json_string.begin(), json_string.end()));
    }
};

// json_schema_validator为module名，必需和生成的so库名一样
BOOST_PYTHON_MODULE(json_schema_validator)
{
    class_<json_validator_python, boost::noncopyable> ("json_validator_python")
            .def("set_root_schema", &json_validator_python::set_root_schema)
            .def("validate", &json_validator_python::validate)
            ;
}
``` 
4. Building the wrapped class for python: 
```
g++ --std=c++11 -fPIC -c jsv_python.cpp \
-I${json-schema-validator_PATH}/src \
-I${nlohmann-json_PATH} \
-I${Boost_PATH}/include \
-I${Python_INCLUDE_PATH}

g++ --std=c++11 -shared \
-L${json-schema-validator_LIB_PATH} \
-L${Python_LIB_PATH} \
-L${Boost_Python_LIB_PATH} \
-lnlohmann_json_schema_validator \
-lboost_python38 -lpython3.8 \
-o json_schema_validator.so jsv_python.o
```
5. Test
```
import json_schema_validator as jsv

validator = jsv.json_validator_python()


isValidator = True
try:
    validator.set_root_schema('{"type":"object", "properties": {"a":{"type": "string"}}}')
    validator.validate('{"a":"1"}');
except:
    isValidator = False

print(isValidator)
```
