### ISSUE TITLE
Dynamic detection of CMake projects

### ISSUE THREAD

**Issue by prince-chrismc** [pboettch/json-schema-validator#122]
To follow up on #119 ...

Sadly I think the find_package might be more common :worried: Most enterprises use package-mangers and most of them are implemented using `find_package()`

I think the original request is reasonable, however using the `nlohmann_json` target to decide whether or not it's being used as a sub-directory could be improved using [CMAKE_PROJECT_NAME](https://cmake.org/cmake/help/v3.12/variable/CMAKE_PROJECT_NAME.html)

The `CMakeLists.txt` is typically written for consumers first with options for local developers. This could be a second solution.

**Comment by pboettch** [comment]
If you could suggest a PR I'd be happy to take a look.

**Comment by pboettch** [comment]
Closing this one as I'm not sure what is requested.
