### ISSUE TITLE
If parent's `default` is empty or null, what to do with a present `default`?

### ISSUE THREAD

**Issue by pboettch** [pboettch/json-schema-validator#124]
This schema with a non-existing (and thus considered `null`) default-value has a child property with a non-null `default`-value.

```JSON
{
    "properties": {
        "address": {
            "type": "object",
            "properties": {
                "street": {
                    "type": "string",
                    "default": "Abbey Road"
                }
            }
        }
    }
}
```

As of today the validator simply ignores that `address` has a default value. But why, it could (or should?) also recursively look for defaults in child-properties and create parent-objects accordingly.

Or should it not?

**Comment by gzzi** [comment]
That would be great! Take extra care maybe to dive on object only if it is required on parent. Someone with one schema to validate multiple different kind of request could have issues otherwise.

**Comment by pboettch** [comment]
gzzi wrote:



Not sure it is a issue. Let me explain a bit our context:

My journey started when I was willing to generate default out of schema (I have seen, even if it is pure annotation, that need seem common). I looked to this library we were already using and discovered that it generate a patch with default value as long as the parent object exist. It is why empty object need to work, the goal of this PR. So to generate default, I do:

    remove all required inside the schema
    start with empty object
    validate with schema
    apply patch
    repeat until patch is a empty list

And it work fine. It is a bit strange and a method on the library that do this job by diving into object not present on the object we are validating would be great (#124).

Of course, another way would be to repeat all member on the default object up to root in the schema. But repeating over and over values doesn't sound good to me.

**Comment by pboettch** [comment]
We could imagine a method which creates a default-instance, with different policies. Full or RequiredOnly or maybe others.

Also, the default value should be valid for the field's schema. But then there would be duplicates, wouldn't it?

```JSON
{
    "properties": {
        "address": {
            "type": "object",
            "properties": {
                "street": {
                    "type": "string",
                    "default": "Abbey Road"
                }
            }
        }
    },
    "default": {
         "street": "Abbey Road"
    }
}
```

How do you handle default value in your schema?

**Comment by gzzi** [comment]
My current solution to avoid duplicate is:

```
{
    "properties": {
        "address": {
            "type": "object",
            "properties": {
                "street": {
                    "type": "string",
                    "default": "Abbey Road"
                }
            }
        }
    },
    "default": { }
}
```

As explained before, I try to apply this schema on a object which is `{}`, it give a patch that look like
```
[ {"op": "add", "path": "/address", "value" : {}}]
```
I apply this patch. Now my object is
```
{
   "address" : {}
}
```

I try to validate, it returns me a patch that add value street Abbey road, I apply it, try to validate again and here the patch is a empty array, I know my default object is complete.

It is a bit a hack.

**Comment by pboettch** [comment]
After reconsideration I think this is out-of-scope of this project. One can easily create a default document from a given schema (recursively diving through it) and then validate it against the schema.
