### ISSUE TITLE
Is nlohmann::json_schema::json_validator::validator  Thread Safe?

### ISSUE THREAD

**Issue by YuanYingdong** [pboettch/json-schema-validator#125]
We are going to use the json_validator::validator in multi-thread environment, do i need to allocate the validator for each thread ?

**Comment by pboettch** [comment]
Instance validation is thread-safe and the same validator-object can be used by different threads:

See the `const`ness of the validate function:

```C++
	json json_validator::validate(const json &) const;
```

Object creation however is not thread-safe. So you should create your validator instance in one (main?) thread once and then use it in your threads.
