### ISSUE TITLE
Enable to use "format":"uri"

### ISSUE THREAD

**Issue by lmussier** [pboettch/json-schema-validator#129]
Hi,

First of all a big thanks for this excellent library.
I have hard time to validate this schema :

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "myUri": {
      "type":"string",
      "format": "uri"
    }
  }
}
```

While validating, the lib output shows  
`a format checker was not provided but a format keyword for this string is present: uri`

Im' pretty convinced this is related to #56, but hte links in the issue does not seems valid anymore (code should have move).

Could you re-explain how to use a format-checker for those types ?

**Comment by pboettch** [comment]
You need to provide a callback a the validator's construction time. A callback is function you provide which gets called when a format-attributed-field is encountered.

There is no real example showing how to use a user-provided format-check. Which is a pity. I will create a simple example using your schema.

**Comment by pboettch** [comment]
Could you check out the master branch, I added a format.cpp in the app-folder which shows a minimalized example of what can be done with the format-callback.

https://github.com/pboettch/json-schema-validator/blob/master/app/format.cpp

**Comment by lmussier** [comment]
Perfact, big thanks ;)
