### ISSUE TITLE
Nesting schemas?

### ISSUE THREAD

**Issue by dvergeylen** [pboettch/json-schema-validator#14]
Hello @pboettch,
Thank you for the job done!

I was wondering how it was possible to insert multiple schemas (nested) in the validator class. As `insert_schema` function is private, only `set_root_schema` is available and I couldn't find a way to do that.

A simplified use case:

File 1, referencing File 2 (below) via `$ref`:
```json
{
  "$schema": "http://json-schema.org/schema",
  "id": "//my_implem/main",
  "type": "object",
  "properties": {
    "type": {
      "description": "Bla bla ",
      "type": "string",
      "enum": ["authenticate", "activate", "get"]
    }
  },
  "switch": [
    {
      "if": { "properties": { "type": {"constant": "authenticate"} } },
      "then": { "properties": { "payload": { "$ref": "//my_implem/authenticate#/definitions/token_payload"} } }
    },
    {
      [... Other stuff here ...]
    }
  ],
  "required": ["type", "payload"]
}
```

File 2, referenced by File 1:
```
{
  "id": "//my_implem/authenticate",
  "definitions": {
    "token_payload": {
      "description": "The required payload associated with the provided 'type' keyword",
      "type": "object",
      "properties": {
        "token": {
          "type": "string",
          "minLength": 196,
          "maxLength": 197
        }
      },
      "required": ["token"],
      "additionalProperties": false
    }
  }
}
```

Is there a way to nest schemas in the validator?

**Comment by pboettch** [comment]
Yes, when the validator is parsing the schema and it finds a `$ref`-key which references an unknown schema it will ultimately call the `loader`-callback you can provide as first argument to the constructor:

```C++
json_validator(std::function<void(const json_uri &, json &)> loader = nullptr,
	               std::function<void(const std::string &, const std::string &)> format = nullptr)
```

In the `json_uri &`-argument you'll find the file you can then load and insert into the `json &`-arg.

However! The URI-class is not very robust it might have some problems with your URLs. See #9

**Comment by dvergeylen** [comment]
Thank you for your reply.

Included and seems to work fine! Thanks :+1:
