### ISSUE TITLE
Validating JSON failed with 'no subschema has succeeded, but one of them is required to validate' error

### ISSUE THREAD

**Issue by grbba** [pboettch/json-schema-validator#142]
Here is my second issue i don't know how to fix.

I have a schema ( [DccEXLayout.json.txt](https://github.com/pboettch/json-schema-validator/files/5864684/DccEXLayout.json.txt) ) and a JSON document ( [SuperSmall.json.txt](https://github.com/pboettch/json-schema-validator/files/5864686/SuperSmall.json.txt)). 

Sorry for the .txt extension. Github doesn't let me upload .json files

The JSON document has been edited in VSC using the schema and there are no problems reported on the validity of this document against the schema. The same goes for the schema against draft-v7.

I tested both files as well on https://www.jsonschemavalidator.net/ and the schema validates against v7, v6 and v4 but not v3 and 2019-09. The json document validates against my schema. 

My program reads the schema and set this schema with set_root_schema without any error. After parsing the document, providing the parsed document to the validate method from the validator i get the  
`no subschema has succeeded, but one of them is required to validate`
error message.

Any ideas why this is happening would be great!

Thanks a lot

**Comment by pboettch** [comment]
I ran your schema and instance with the small command-line tool included in the build-dir:

```Bash
$ ../../build/json-schema-validate schema.json < instance.json 
document is valid
```

Could you try to run the same tool to see whether there is problem with this library on your platform? If this works for you as well, there is a problem in your code loading the instance or maybe the schema.

**Comment by grbba** [comment]
ok first thanks for the tip about the little tool :) And indeed it says its valid as for you. Tried it on a couple of other test json documents and they all work so it in the code ... 

So that's what i am doing right now
```
int main()
{
    std::string dccExSchema;
    std::ifstream layoutFile(fLayout);
    dccexlayout::DccExLayout layout;
    json schema;
    json_validator validator;

    Diag::setLogLevel(LOGV_ERROR);
    Diag::setFileInfo(false);   

    INFO("Welcome to the DCC++ EX Layout generator!\n");
    INFO("Reading DccExLayout schema ...");
    
   // read schema from file
   readJsonFile(dccSchema, &dccExSchema);

    INFO("Validating DccExLayout schema ...");
    std::stringstream j(dccExSchema);
    try
    {
        j >> schema;
    }
    catch (const std::exception &e)
    {
        ERR("Validation of schema failed: %s", e.what());
        ERR("Validation failed at: [%s] while parsing schema", j.tellg());
        return EXIT_FAILURE;
    }

    INFO("Initializing DccExLayout schema for layout parsing ...");
    try
    {
        validator.set_root_schema(schema); // insert root-schema
    }
    catch (const std::exception &e)
    {
        ERR("Schema initialization failed: %s", e.what());
        return EXIT_FAILURE;
    }

    INFO("Loading & Parsing Layout description ... ");

    try
    {
        layout = nlohmann::json::parse(layoutFile);
    }
    catch (json::parse_error &e)
    {
        ERR("Loading & parsing of the layout failed: %s", e.what());
        return EXIT_FAILURE;
    }

    INFO("Validating Layout description ... ");
    try
    {
        validator.validate(layout);
    }
    catch (const std::exception &e)
    {
        ERR("Validation failed: %s", e.what());
        return EXIT_FAILURE;
    }

    // Build the Layout Graph
    buildLayout(&layout);

    return EXIT_SUCCESS;
}
```
Are there any obvious errors ? The main difference from your examples is that i feed the schema from a stringstream instead of directly from the file containing the schema. Maybe this is the isssue ?

**Comment by grbba** [comment]
Actually reading it from the stringstream or directly from the file doesn't change anything unfortunately ...

**Comment by pboettch** [comment]
I took some pleasure to fill in the gaps of your snippet and have to tell you, it works for me on my machine:

Here is my full code

```C++
#include <fstream>
#include <sstream>
#include <string>
#include <streambuf>

#include <cstdio>

#include <nlohmann/json-schema.hpp>

using nlohmann::json;
using nlohmann::json_schema::json_validator;

namespace dccexlayout
{
typedef json DccExLayout;
} // namespace dccexlayout

void buildLayout(dccexlayout::DccExLayout *) {}

namespace Diag
{
#define LOGV_ERROR 1
void setLogLevel(int)
{
}
void setFileInfo(bool) {}

#define INFO(args...) \
	do {              \
		printf(args); \
		printf("\n"); \
	} while (0)
#define ERR(args...) \
	do {             \
		printf(args); \
		printf("\n"); \
	} while (0)

} // namespace Diag

void readJsonFile(const std::string &schema_filename, std::string *schema)
{
	std::ifstream schema_file(schema_filename);

	*schema = std::string(std::istreambuf_iterator<char>(schema_file),
                 std::istreambuf_iterator<char>());
}

int main()
{
	auto dccSchema = "path/upstream/json-schema-validator/test/issue-142/schema.json";
	auto fLayout = "path/upstream/json-schema-validator/test/issue-142/instance.json";

	std::string dccExSchema;
	std::ifstream layoutFile(fLayout);
	dccexlayout::DccExLayout layout;
	json schema;
	json_validator validator;

	Diag::setLogLevel(LOGV_ERROR);
	Diag::setFileInfo(false);

	INFO("Welcome to the DCC++ EX Layout generator!\n");
	INFO("Reading DccExLayout schema ...");

	// read schema from file
	readJsonFile(dccSchema, &dccExSchema);

	INFO("Validating DccExLayout schema ...");
	std::stringstream j(dccExSchema);
	try {
		j >> schema;
	} catch (const std::exception &e) {
		ERR("Validation of schema failed: %s", e.what());
		ERR("Validation failed at: [%d] while parsing schema", j.tellg());
		return EXIT_FAILURE;
	}

	INFO("Initializing DccExLayout schema for layout parsing ...");
	try {
		validator.set_root_schema(schema); // insert root-schema
	} catch (const std::exception &e) {
		ERR("Schema initialization failed: %s", e.what());
		return EXIT_FAILURE;
	}

	INFO("Loading & Parsing Layout description ... ");

	try {
		layout = nlohmann::json::parse(layoutFile);
	} catch (json::parse_error &e) {
		ERR("Loading & parsing of the layout failed: %s", e.what());
		return EXIT_FAILURE;
	}

	INFO("Validating Layout description ... ");
	try {
		validator.validate(layout);
	} catch (const std::exception &e) {
		ERR("Validation failed: %s", e.what());
		return EXIT_FAILURE;
	}

	// Build the Layout Graph
	buildLayout(&layout);

	return EXIT_SUCCESS;
}
```

**Comment by grbba** [comment]
That is really cool thanks a lot :) & I found the issue ... 

I use quicktype.io ( from the VSC module they provide ) to generate the C++ object model ( with some minor changes added e.g. changing the namespace name and adding a root class with some properties i need), from the schema ( they are using the nlohmann library). 

So when i call the parser actually the json file gets parsed into the root object of the model `dccexlayout::DccExLayout layout`; which is actually not of JSON type ( but it must be as the parse call only return a json - there is a link somewhere but i couldn't figure that out yet ) so when i actually provide a json typed variable to the parse and feed that ( just like you did using the typedef ) it works.

As i fed this one ( stupidly assuming it must be of type json ) into the validator the behavior gets undefined i guess and reports the error i encountered. 

I wonder why i can actually return a json type value from parse into this dccexlayout::DccExLayout layout via the quicktype. There doesn't seem to be an obvious link.

**Comment by pboettch** [comment]
You cannot, probably. It's nlohmann::json which accepts a type which your class returns (maybe an cast-operator() to string?) and nlohmann parses that as it is json. But this is not the instance you where thinking it is.
