### ISSUE TITLE
support uri format validation of string properties

### ISSUE THREAD

**Issue by linus-gates** [pboettch/json-schema-validator#158]
I would like to use the "uri" format to validate a string property however it's currently unsupported.
According to [json schema draft 7](https://json-schema.org/understanding-json-schema/reference/string.html#format) the string should be validated as specified by [rfc3986](https://tools.ietf.org/html/rfc3986)

Thanks in advance,
linus

**Comment by pboettch** [comment]
If you can contribute this, do not hesitate. There is a `default_string_format_check()`-function in the library which already checks some of the optional formats. This functions just sits there and waits for more features.
