### ISSUE TITLE
CMake Install Error

### ISSUE THREAD

**Issue by lkersting** [pboettch/json-schema-validator#159]
I include json-schema-validator and nlohmann_json as subdirectories in my project, but the CMake options currently don't allow me to install json-schema-validator when it is included as a subdirectory. Since I have libraries that depend on the nlohmann_json_schema_validator library I get a CMake error when trying to configure my code for installation:
~~~
CMake Error: install(EXPORT "CodeTargets" ...) includes target "input_parsers" which requires target "nlohmann_json_schema_validator" that is not in any export set.
~~~

The problem is caused by line 62 in the top level [CMakeLists.txt](https://github.com/pboettch/json-schema-validator/blob/master/CMakeLists.txt#L62), which sets the `JSON_VALIDATOR_INSTALL` variable to `OFF`. If I comment out this line everything works fine.

May I suggest changing `JSON_VALIDATOR_INSTALL` to a CMake option which would allow users to decide if the code should be installed or not. Then removing line 62 (and possibly 71) so it doesn't override the user's settings.

**Comment by pboettch** [comment]
I has become a pain in the a** all the possibilities we have with integration à CMake-project in another CMake-project.

I switch every project to use ExternalProject even for CMake-projects. In this way they are isolated from the parent project and we can still use all features.

There is basically no advantage when using `add_subdirectory()` over `ExternalProject_Add()` except some more line of CMake to be written (creating INTERFACE-target and selecting files to be installed by the parent project).

If you are able to provide a patch which solves your problem by not breaking other features please submit a pull-request. Thanks.

**Comment by pboettch** [comment]
Please do open a PR to solve your issue if you can, otherwise do not hesitate to re-open this one if still necessary.
