### ISSUE TITLE
Cannot be used with installs if json is not installed

### ISSUE THREAD

**Issue by Finkman** [pboettch/json-schema-validator#164]
In case JSON is not installed, this is detected by the validator lib and the install-feature is disabled.

That leads to the following issue:

We have a super project that contains JSON and the Validator as sub-projects. The super project itself needs the ability to be installed. For that reason CMake would implicitly install JSON as well. But, since the Validator detects that JSON is not installed, but used next to it, it disables the install feature by setting `JSON_VALIDATOR_INSTALL OFF`.
That breaks CMake build chain, because the validator is a dependency that is not in the export list.

Without setting the `JSON_VALIDATOR_INSTALL OFF` everything works nice.

**Comment by pboettch** [comment]
Related? https://github.com/pboettch/json-schema-validator/pull/162

**Comment by Finkman** [comment]
Is duplicate of #162
