### ISSUE TITLE
segmentation fault in json_validator::validate if using _LIBCPP_DEBUG

### ISSUE THREAD

**Issue by eike-fokken** [pboettch/json-schema-validator#177]
Hi!

If I compile with clang, libc++ (llvms implementation of the C++ standard library) and there with the debug version, there is a segfault in `json_validator::validate`.

The essence is this:
If you compile with `clang++ -stdlib=libc++ -D_LIBCPP_DEBUG=1`, depending on the (valid) schema provided, there are segfaults in `validate`.

```c++
int main() {
json j = ...;
json schema = ...;
  // check that the schema itself is valid:
  json_validator validator;

  try {
    validator.set_root_schema(schema);
  } catch (const std::exception &e) {
    std::cout << "Couldn't validate the data, because the schema itself is faulty: "
      << e.what() << "\n";
  }
  // check that the schema itself is valid:
  json_validator validator;
  validator.set_root_schema(schema);

  // validate:
  validator.validate(j);
    }
```

Unfortunately I am not good with schemas, therefore my minimal example is not thaaat minimal and I have put it into a git repo:

https://github.com/eike-fokken/debug_segfault_libcpp_debug

you can trigger the segfault by:

```sh
git clone --recursive git@github.com:eike-fokken/debug_segfault_libcpp_debug.git
cd debug_segfault_libcpp_debug
cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++
cmake --build build && build/test 
```

**Comment by eike-fokken** [comment]
I'm not sure whether it helps, but here are backtraces from gdb, one normal one and one full backtrace.

[backtrace.txt](https://github.com/pboettch/json-schema-validator/files/7363174/backtrace.txt)

[full_backtrace.txt](https://github.com/pboettch/json-schema-validator/files/7363177/full_backtrace.txt)

**Comment by pboettch** [comment]
And your schema seems not work. I'm getting the error (where it crashes) and if I read the schema correctly it should be fine (there is one value where x = 0 and one where x = 1).

**Comment by pboettch** [comment]
I created a snippet which crashes for me (no more dependency to json or schema):
```C++
#include <iostream>

int main()
{
	std::pair<bool, double> minimum_{true, 1};
	std::cerr << "instance is below minimum of " + std::to_string(minimum_.second) << "\n";

	return 0;
}
```

**Comment by eike-fokken** [comment]
> Instead of using `maxmum==minimum`, could you use `const` in your schema?

I guess? I have really no real idea about schemas. A colleague of mine who is no longer in my group wrote our schema-generation code. Right now I don't really have time to dive into it. Is it a bad idea to use minimum==maximum?

**Comment by eike-fokken** [comment]
> Does it crash for you?

It does. That means, it's a bug with libcpp, right?

**Comment by pboettch** [comment]
You're saying that it is `const char *` + something. I think it is rather related to the `std::pair` and `std::to_string`.

**Comment by pboettch** [comment]
I can't use `<<` because I pass it as an argument to a function which takes a string - so I have to concatenate it.

And yes, fixing something in my library which is clearly a serious bug (if it is) in a standard-lib.

The problem seems to disappear if you use a straight double instead of the pair's second.
