### ISSUE TITLE
Using draft7_schema_buildin schema to validate schema crashes

### ISSUE THREAD

**Issue by vrince** [pboettch/json-schema-validator#178]
Hi All,

Currently trying to use `json-schema-validator` to validate if schema pass by user follows draft7. To do so naively I used ` nlohmann::json_schema::draft7_schema_builtin` as a root schema then pass the user schema to `validator.validate` unfortunately this leads to a segfault deep into `nlohmann` bowels. 

There is certainly something I do wrong / don't understand. Any help is appreciated.

To reproduce here is a modified version of the `format.cpp` example (because we need validation for `uri` type) : 

```cpp
#include <iostream>

#include <nlohmann/json-schema.hpp>

using nlohmann::json;
using nlohmann::json_schema::json_validator;

// The schema is defined based upon a string literal
static json uri_schema = R"(
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "myUri": {
      "type":"string",
      "format": "uri"
    }
  }
})"_json;

// The people are defined with brace initialization
static json good_uri = {{"myUri", "http://hostname.com/"}};
static json bad_uri = {{"myUri", "http:/hostname.com/"}};

static void uri_format_checker(const std::string &format, const std::string &value)
{
	if (format == "uri") {
		if (value.find("://") == std::string::npos)
			throw std::invalid_argument("URI does not contain :// - invalid");
	} else
		throw std::logic_error("Don't know how to validate " + format);
}

int main()
{
	json_validator validator(nullptr, uri_format_checker); // create validator

	std::cout << nlohmann::json_schema::draft7_schema_builtin.dump(2) << std::endl;

	try {
		validator.set_root_schema(nlohmann::json_schema::draft7_schema_builtin); // insert root-schema
	} catch (const std::exception &e) {
		std::cerr << "Validation of schema failed, here is why: " << e.what() << "\n";
		return EXIT_FAILURE;
	}

	try {
		validator.validate(uri_schema);
	} catch (const std::exception &e) {
		std::cerr << "Validation expectedly failed, here is why: " << e.what() << "\n";
	}

	return EXIT_SUCCESS;
}
```

Tested / reproduced with `master` & `2.1.0`.

I can provide a backtrace/call stack but this is very long ...

Best.

**Comment by vrince** [comment]
Thank you for taking the time to look into it, maybe can you share what version of `nlohmann::json` you are using? I'm on tag `v3.10.4`.

**Comment by pboettch** [comment]
Same here.

In your code, at which place does it crash? Upload the crash-backtrace as a file, please.

**Comment by vrince** [comment]
Creating a `meta-validate` example to reproduce the behavior, cloned mater again, get `nlohmann:json` (`3.8.0`) with hunter no crash ... so investigating ...
