### ISSUE TITLE
Exlcusive Min/Max Error

### ISSUE THREAD

**Issue by lkersting** [pboettch/json-schema-validator#182]
The error for exclusive minimum/maximum is the same as the error for minimum/maximum. This can be confusing when the value is exactly at the min/max.

For the schema entry like:
~~~yaml
"DENSITY": {
  "type": "number",
  "exclusiveMinimum": 0
}
~~~
You would get something like the following error for an entry of 0.0:
~~~
DENSITY: 0.0 -- instance is below minimum of 0.000000
~~~

This can be confusing since 0.0 is actually not below the minimum but at the minimum.

I propose updating the error message for exclusive minimum and maximum to:
~~~
 instance is below or equals minimum of ...
~~~
and
~~~
instance exceeds or equals maximum of ...
~~~

**Comment by pboettch** [comment]
Good idea. Would you be able to create a PR?

**Comment by lkersting** [comment]
Just added a PR
