### ISSUE TITLE
shared object file symlink version confusion

### ISSUE THREAD

**Issue by kopp** [pboettch/json-schema-validator#186]
When I build and install the library, (release 2.1.0) the `lib` folder looks like this:

```
├── libnlohmann_json_schema_validator.so -> libnlohmann_json_schema_validator.so.1
├── libnlohmann_json_schema_validator.so.1 -> libnlohmann_json_schema_validator.so.2.1.0
└── libnlohmann_json_schema_validator.so.2.1.0
```

So you see the shared object `so.2.1.0` symlinks to the shared object `so.1`.  Is this intended (because the current .so is still compatible with the "old" api) or was bumping the `SOVERSION` simply forgotten when switching to the major version 2?
(The [CMakeLists.txt](https://github.com/pboettch/json-schema-validator/blob/master/CMakeLists.txt#L45) file currently has `SOVERSION 1` hard coded since 3 years.)  If it is the latter, it would be awesome if you could add a brief comment in the CMakeLists.txt file stating that this is intended.

**Comment by pboettch** [comment]
I'd say it was forgotten to bump the version. I'll soon will make a new version where the CMake-file has changed quite a bit (still under reflection) - would be good to change it.

Even if API is compatible, it's not a good idea to use the old version.
