### ISSUE TITLE
Allow to disable tests / examples

### ISSUE THREAD

**Issue by Sil3ntStorm** [pboettch/json-schema-validator#195]
It appears that it is impossible to disable building the examples and tests.

There are options for it with `JSON_VALIDATOR_BUILD_EXAMPLES` and `JSON_VALIDATOR_BUILD_TESTS`, however they get ignored completely if they are set, as they're overwritten to be enabled in [CMakeLists.txt#L48-L59](https://github.com/pboettch/json-schema-validator/blob/master/CMakeLists.txt#L48-L59), which effectively makes it so you cannot disable them.

However you want to do it, it should be possible to disable the tests / examples.

**Comment by inkychris** [comment]
This cuts both ways. I have json-schema as a submodule and can't build the tests or examples without modifying this project's CMake config.
