### ISSUE TITLE
Map remote uri path to a schema?

### ISSUE THREAD

**Issue by sam20908** [pboettch/json-schema-validator#196]
I'm looking to transition to this library to validate schemas from rapidjson, but I wasn't sure if this provides a way for the user to resolve uris on their own. For example, I have schemas embed into the application, so they don't actually exist in the path, but rapidjson allows me to create a map to resolve them via https://rapidjson.org/md_doc_schema.html#Remote.

Is the same thing possible with this library? Thanks!

**Comment by pboettch** [comment]
Yes, it does. Via a callable (`loader`) provided at the instantiation of the validator by you. It is called for every schema-ref which cannot be resolved by the provided schemas.

Checkout the small example app here: https://github.com/pboettch/json-schema-validator/blob/master/app/json-schema-validate.cpp#L67

**Comment by sam20908** [comment]
Yep, that works!
