### ISSUE TITLE
Compatability issue with newest version of json

### ISSUE THREAD

**Issue by GKJose** [pboettch/json-schema-validator#198]
In json-validator.cpp, line 218, uri.pointer() != "" now throws an error.
Solution: uri.pointer().to_string() != ""

**Comment by mingthemad** [comment]
Just found the same problem on Ubuntu 20.04.3 LTS using gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

~/json-schema-validator/build$ make |& more
[  2%] Building CXX object CMakeFiles/nlohmann_json_schema_validator.dir/src/json-validator.cpp.o
/home/a_build/json-schema-validator/src/json-validator.cpp: In member function 'std::shared_ptr<{anonymous}::schema> nlohmann::json_schema::root_schema::get_or_create_ref(const nlohmann::json_uri&)':
/home/a_build/json-schema-validator/src/json-validator.cpp:219:21: error: no match for 'operator!=' (operand types are 'const json_pointer' {aka 'const nlohmann::json_pointer<std::__cxx11::basic_string<char> >'} and 'const char [1]')
  219 |   if (uri.pointer() != "") {
      |       ~~~~~~~~~~~~~ ^~ ~~
      |                  |     |
      |                  |     const char [1]
      |                  const json_pointer {aka const nlohmann::json_pointer<std::__cxx11::basic_string<char> >}
In file included from /home/a_build/json-schema-validator/src/nlohmann/json-schema.hpp:24,
                 from /home/a_build/json-schema-validator/src/json-validator.cpp:9:
/usr/local/include/nlohmann/json.hpp:13337:13: note: candidate: 'template<class RefStringTypeLhs, class RefStringTypeRhs> bool nlohmann::operator!=(const nlohmann::json_pointer<RefStringType>&, const nlohmann::json_pointer<RefStringTypeRhs>&)'
13337 | inline bool operator!=(json_pointer<RefStringTypeLhs> const& lhs,
      |             ^~~~~~~~
/usr/local/include/nlohmann/json.hpp:13337:13: note:   template argument deduction/substitution failed:
/home/a_build/json-schema-validator/src/json-validator.cpp:219:24: note:   mismatched types 'const nlohmann::json_pointer<RefStringTypeRhs>' and 'const char [1]'
  219 |   if (uri.pointer() != "") {
      |                        ^~
In file included from /usr/include/c++/9/regex:62,
                 from /home/a_build/json-schema-validator/src/json-validator.cpp:30:
/usr/include/c++/9/bits/regex.h:1037:5: note: candidate: 'template<class _BiIter> bool std::__cxx11::operator!=(const std::__cxx11::sub_match<_BiIter>&, const std::__cxx11::sub_match<_BiIter>&)'
 1037 |     operator!=(const sub_match<_BiIter>& __lhs, const sub_match<_BiIter>& __rhs)
      |     ^~~~~~~~
/usr/include/c++/9/bits/regex.h:1037:5: note:   template argument deduction/substitution failed:
/home/a_build/json-schema-validator/src/json-validator.cpp:219:24: note:   'const json_pointer' {aka 'const nlohmann::json_pointer<std::__cxx11::basic_string<char> >'} is not derived from 'const std::__cxx11::sub_match<_BiIter>'
  219 |   if (uri.pointer() != "") {
      |                        ^~
In file included from /usr/include/c++/9/regex:62,
                 from /home/a_build/json-schema-validator/src/json-validator.cpp:30:
/usr/include/c++/9/bits/regex.h:1112:5: note: candidate: 'template<class _Bi_iter, class _Ch_traits, class _Ch_alloc> bool std::__cxx11::operator!=(std::__cxx11::__sub_match_string<_Bi_iter, _Ch_traits, _Ch_alloc>&, const std::__cxx11::sub_match<_BiIter>&)'
 1112 |     operator!=(const __sub_match_string<_Bi_iter, _Ch_traits, _Ch_alloc>& __lhs,
      |     ^~~~~~~~
/usr/include/c++/9/bits/regex.h:1112:5: note:   template argument deduction/substitution failed:
/home/a_build/json-schema-validator/src/json-validator.cpp:219:24: note:   'const json_pointer' {aka 'const nlohmann::json_pointer<std::__cxx11::basic_string<char> >'} is not derived from 'std::__cxx11::__sub_match_string<_Bi_iter, _Ch_traits, _Ch_alloc>'
  219 |   if (uri.pointer() != "") {
      |                        ^~
In file included from /usr/include/c++/9/regex:62,
                 from /home/a_build/json-schema-validator/src/json-validator.cpp:30:
/usr/include/c++/9/bits/regex.h:1186:5: note: candidate: 'template<class _Bi_iter, class _Ch_traits, class _Ch_alloc> bool std::__cxx11::operator!=(const std::__cxx11::sub_match<_BiIter>&, std::__cxx11::__sub_match_string<_Bi_iter, _Ch_traits, _Ch_alloc>&)'
 1186 |     operator!=(const sub_match<_Bi_iter>& __lhs,
      |     ^~~~~~~~
/usr/include/c++/9/bits/regex.h:1186:5: note:   template argument deduction/substitution failed:
/home/a_build/json-schema-validator/src/json-validator.cpp:219:24: note:   'const json_pointer' {aka 'const nlohmann::json_pointer<std::__cxx11::basic_string<char> >'} is not derived from 'const std::__cxx11::sub_match<_BiIter>'
  219 |   if (uri.pointer() != "") {
      |                        ^~
In file included from /usr/include/c++/9/regex:62,
                 from /home/a_build/json-schema-validator/src/json-validator.cpp:30:
/usr/include/c++/9/bits/regex.h:1260:5: note: candidate: 'template<class _Bi_iter> bool std::__cxx11::operator!=(const typename std::iterator_traits<_Iter>::value_type*, const std::__cxx11::sub_match<_BiIter>&)'
 1260 |     operator!=(typename iterator_traits<_Bi_iter>::value_type const* __lhs,
      |     ^~~~~~~~
/usr/include/c++/9/bits/regex.h:1260:5: note:   template argument deduction/substitution failed:
/home/a_build/json-schema-validator/src/json-validator.cpp:219:24: note:   mismatched types 'const std::__cxx11::sub_match<_BiIter>' and 'const char [1]'
  219 |   if (uri.pointer() != "") {

**Comment by pboettch** [comment]
Could propose a backward compatible patch via a pull request?
