### ISSUE TITLE
Question: was the default branch recently renamed to "main"?

### ISSUE THREAD

**Issue by greenfoo** [pboettch/json-schema-validator#204]
Hi, sorry for opening a ticket for a question but I'm trying to figure out why Yocto's build system broke on this repo and it might be related to the default branch name.

Was the default branch name changed from "master" to "main" recently (~in the last 24 hours)? (that would explain what I'm seeing).

Thanks!

**Comment by pboettch** [comment]
Yes. Sorry. I had no mean to inform users or at least I'm not aware of any good way to do so on GitHub.

On June 6, 2022 5:55:46 PM GMT+02:00, greenfoo ***@***.***> wrote:
>Hi, sorry for opening a ticket for a question but I'm trying to figure out why Yocto's build system broke on this repo and it might be related to the default branch name.
>
>Was the default branch name changed from "master" to "main" recently (~in the last 24 hours)? (that would explain what I'm seeing).
>
>Thanks!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pboettch/json-schema-validator/issues/204
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pboettch** [comment]
Sorry for the trouble. I really wasn't aware (and still not) how to do this smoothly.

**Comment by greenfoo** [comment]
Hi @pboettch , I know this might be too much to ask (so feel free to ignore my request), but ... would it be possible to revert back to "master" for a few weeks until I figure out how to fix our internal build system?

It's not trivial to change the reference due to the way the build system works and it's causing a lot of headaches and emails :)

Thanks.

**Comment by greenfoo** [comment]
Ok, it will work with both in our work around :)

Are you planning on leaving "master" for others?

**Comment by pboettch** [comment]
I'm going to drop the master-branch once the release is done (about to happen)
