### ISSUE TITLE
Provide up-to-date release to better support vcpkg

### ISSUE THREAD

**Issue by SamVanheer** [pboettch/json-schema-validator#207]
The latest release of this library dates back to 2 years ago.

vcpkg ties port updates to releases for convenience, so it would be helpful if a new release were made available to allow the vcpkg port to be updated as well.

See here for the vcpkg port configuration: https://github.com/microsoft/vcpkg/tree/master/ports/json-schema-validator

The patches provided there might be worth a look to see if they can be applied to the project directly if they are still needed.

When a release is available it would be great if you could also request an update to the port so they can add the new release.

See also the issue and pull request that added the library:
https://github.com/microsoft/vcpkg/issues/11080
https://github.com/microsoft/vcpkg/pull/11599

**Comment by pboettch** [comment]
Well, I wasn't even aware that this project is provided by vcpkg. I'm relatively out of time. If someone could take care of that it would be great help.

**Comment by SamVanheer** [comment]
I've checked the vcpkg patches to see which ones are still relevant:
* cmake-find-package and forward-find-package are no longer needed since nlohmann_json is explicitly added as a dependency
* fix-ambiguous-assignment was fixed [here](https://github.com/pboettch/json-schema-validator/commit/0097de3c54e90811103f75b4fc48b568f9e9585f)

So all that's needed is for a new version to be released, then a request to update the port should be made here: https://github.com/microsoft/vcpkg/issues/new/choose

They'll take care of the rest, assuming there's no problems the new version should be made available shortly.

Is there anything else that needs doing before a new release can be made available?

**Comment by SamVanheer** [comment]
On second thought, `forward-find-package` uses `find_dependency` instead of `find_package` which causes it to use the parameters provided for the original `find_package` call. That's probably worth changing.

**Comment by SamVanheer** [comment]
Once #221 has been merged all vcpkg patches will have been merged. All that's left then is to do a new tag release to allow the vcpkg port to be updated.

**Comment by SamVanheer** [comment]
I've been experimenting with making the HEAD commit into a port and it looks like #195 will be a problem. Because the tests and examples are forced on if it's the root file vcpkg will print these warnings:

>  The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.
>
>    D:/a/halflife-unified-sdk/halflife-unified-sdk/vcpkg/packages/json-schema-validator_x86-windows/bin/json-schema-validate.exe
>    D:/a/halflife-unified-sdk/halflife-unified-sdk/vcpkg/packages/json-schema-validator_x86-windows/bin/readme-json-schema.exe
>
>The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.
>
>    D:/a/halflife-unified-sdk/halflife-unified-sdk/vcpkg/packages/json-schema-validator_x86-windows/debug/bin/json-schema-validate.exe
>    D:/a/halflife-unified-sdk/halflife-unified-sdk/vcpkg/packages/json-schema-validator_x86-windows/debug/bin/readme-json->schema.exe

I will look into resolving this problem.

**Comment by pboettch** [comment]
If we disable tests and bins by default, I'd be OK with that if it helps.

**Comment by SamVanheer** [comment]
I've created a pull request that fixes the issue with no downsides.

**Comment by pboettch** [comment]
Release about to be pushed

**Comment by SamVanheer** [comment]
I've made the update request here: https://github.com/microsoft/vcpkg/issues/28028
