### ISSUE TITLE
Default values of all "oneOf" sub-schema are inserted in patch 

### ISSUE THREAD

**Issue by didier-brizet** [pboettch/json-schema-validator#229]
Only the default value of one of "oneOf" sub-schema must be inserted in patch returned by `json_validator::validate`.

For instance, the validation of ``` {"name": "bar"} ``` against the following JSON schema:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "oneOf": [
        {
            "type": "object",
            "properties": {
                "name": {
                    "enum": "foo"
                },
                "code": {
                    "const": 1,
                    "default": 1
                }
            }
        },
        {
            "type": "object",
            "properties": {
                "name": {
                    "enum": "bar"
                },
                "code": {
                    "const": 2,
                    "default": 2
                }
            }
        }
    ]
}
````

must returns the patch ```[{"op":"add","path":"/code","value":2}]``` but the following patch is returned:
```[{"op":"add","path":"/code","value":1},{"op":"add","path":"/code","value":2}]```

**Comment by didier-brizet** [comment]
I propose the following patch:

[issue_229.txt](https://github.com/pboettch/json-schema-validator/files/9656902/issue_229.txt)

**Comment by UX3D-becher** [comment]
@pboettch We have the same issue with a complex schema, is there anything that still needs to be done in the PR before it can be merged?

**Comment by pboettch** [comment]
It's a huge change. Hard to review. Especially if you're not convinced of the handling of default values _inside_ the validator.

I'd rather prefer to have an outside-of-the-validator solution of default-value-handling. But this is off-topic for this PR.

**Comment by pboettch** [comment]
I won't accept big changes anymore on patch creation concerning default values. I'm not convinced that this library is the right place. Or at least it should not be integrated in the code as it is today.
