### ISSUE TITLE
Compatibility with latest nlohmann::json?

### ISSUE THREAD

**Issue by Sil3ntStorm** [pboettch/json-schema-validator#236]
There seems to have been a few changes to nlohmann::json, which causes this library to use deprecated functions, causing issues during compilation.

**Comment by pboettch** [comment]
With latest, do you mean 3.11.2? Or the develop-branch?

**Comment by Sil3ntStorm** [comment]
latest release tag yes.

**Comment by pboettch** [comment]
I just build the main-branch of this project against json 3.11.2 and there was no warning or error.

Please post your compile log.

**Comment by Sil3ntStorm** [comment]
json-scheme.hpp:64
json-scheme.hpp:84
Warning	C4996	'nlohmann::json_abi_v3_11_2::json_pointer<StringType>::operator std::basic_string<char,std::char_traits<char>,std::allocator<char>>': Since 3.11.0; use to_string()

**Comment by pboettch** [comment]
The main-branch of this project is up to date regarding this requirement.

**Comment by Sil3ntStorm** [comment]
Would you mind creating a new release? Package managers (such as vcpkg or conan) usually work with release tags only and do not track branches.

**Comment by pboettch** [comment]
OK, I'm waiting for #235, but yeah it's time
