### ISSUE TITLE
Incompatible with nlohmann::json versions in Ubuntu Focal and RedHat 8

### ISSUE THREAD

**Issue by orensbruli** [pboettch/json-schema-validator#237]
Ubuntu Focal, RedHat 8, fedora 32, and some other distributions still have nlohmann::json libs <= 3.8
After the 2.1.0 release, some important fixes have been done to the CMakeList.txt that could be very useful to backport.
Specially d3b0d327cd32da5ef8ed5fe245d08a1fe53e62e3 and 639e09b6f96aeaa7e49fd1e4eb9bab6bfaa6419d fixes some problems with redistributable installs.

**Comment by pboettch** [comment]
<= 3.8 you're saying, so this project is still compatible? I'm about to make a tag and thus a release.

**Comment by orensbruli** [comment]
No, it's not compatible with those distributions since this commit
https://github.com/pboettch/json-schema-validator/commit/a632d2707b98b98867ae2b1830a55b5aab69b63c Added support to validate binary only in json-dev >=3.8
https://github.com/pboettch/json-schema-validator/commit/5ef4f903af055550e06955973a193e17efded896 Last commit not depending on json-dev >= 3.8

**Comment by pboettch** [comment]
I see, I'll try to fix it.

**Comment by pboettch** [comment]
I just build the 2.2.0 release with 3.8.0. 

Do you need < 3.8.0? (You always wrote <= (less or equal)) hence my confusion?

**Comment by pboettch** [comment]
I'm unable to provide support for JSON < 3.8.0 (soon 3 years old) in this project. I'm willing to merge a release-branch with all relevant backported changes if you can provide.
