### ISSUE TITLE
Validation Error from null field

### ISSUE THREAD

**Issue by ZenixineZ** [pboettch/json-schema-validator#254]
Schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "field1": { "type": "string" },
    "field2": { "type": "string" }
  },
  "required": ["field1"]
}
```

Object:
```
{
  "field1": "test", 
  "field2": null 
}
```
Error:
`At /field2 of null - unexpected instance type`

Is there anyway for it to allow null values for non-required fields?

**Comment by pboettch** [comment]
This is more a question for Stackoverflow. 

Try: `"field2": { "type": ["null", "string"] }

**Comment by ZenixineZ** [comment]
My god I feel foolish. Thank you for the response and sorry I bothered you
