### ISSUE TITLE
Yaml validation

### ISSUE THREAD

**Issue by LecrisUT** [pboettch/json-schema-validator#263]
Since json schema apply to yaml files as well, it would be nice to have this one be compatible with a yaml parser as well.

**Comment by pboettch** [comment]
If there is a parser which loads yaml to nlohmann::json, let's go.

The question is actually, should we add a yaml-parser to nlohmann::json (as it also support several binary structures leading to JSON).

**Comment by LecrisUT** [comment]
Nlohmann last said that he will not be able to maintain it, but maybe if we can propose a modular system with proper ci and code-owner for reviewing, he might change his mind on this. I am all up for having a more centralized api interface for these

**Comment by pboettch** [comment]
I think you have to see that with Nils. I'm closing this, as YAML would work here directly if nlohmann::json supports it.
