### ISSUE TITLE
validate_numeric doesn't work well for 64-bit integers

### ISSUE THREAD

**Issue by RPGillespie6** [pboettch/json-schema-validator#27]
Current implementation uses double for all numeric validation. However, this is not sufficient when dealing with integers. 

Take the following example:

```c++
static json time_schema = R"(
{
    "properties": {
        "gps_time": {
            "type": "number",
            "minimum": 0,
            "maximum": 4294967295 //UINT32_MAX
        },
    },
    "required": [
        "gps_time"
    ],
    "type": "object"
}
)"_json;

static json gps_cmd = {
    {"gps_time", 4294967296} //passes validation even though it's > maximum
};
```

I am willing to create a PR for this, just creating the issue for tracking.

**Comment by pboettch** [comment]
I pushed a fix on master.

The problem was not that double is used internally, but that I was getting the numeric values as `int` and `unsigned` which are 32-bit only. So your `UINT32_MAX+1`  became 0. Now every numeric value is retrieved as `double`.

**Comment by RPGillespie6** [comment]
This fix is probably okay for now, but double is not precise enough to do 64-bit integer comparisons.

Consider the following:

```c++
#include <iostream>

using namespace std;

int main() {
  uint64_t x = 99999999999999997;
  uint64_t y = 99999999999999999;
  double a = x;
  double b = y;
  cout << to_string(x == y) << " " << to_string(a == b) << endl;
}
```

In this case, the integer comparison fails, but the double comparison passes.

It would be nice if this library used `uint64_t` for integer comparisons and `double` for floating point comparisons (since JSON Schema differentiates between the two). Not sure if `nlohmann/json` provides a hook for determining a given field is integer vs. numeric, though.
