### ISSUE TITLE
Sofile name has changed

### ISSUE THREAD

**Issue by EGuesnet** [pboettch/json-schema-validator#270]
Hi,
On release 2.2.0, or up to yesterday on main, the lib was released on Linux as `libnlohmann_json_schema_validator.so` . Probably due to PR #262, the name is now `libnlohmann_json_validator.so` (without `schema`).
Is this voluntary, or a mistake?
Thanks.

**Comment by EGuesnet** [comment]
Some details:

On https://github.com/pboettch/json-schema-validator/blob/main/CMakeLists.txt#L140, 

```
set_target_properties(nlohmann_json_schema_validator PROPERTIES
        VERSION ${PROJECT_VERSION}
        SOVERSION ${PROJECT_VERSION_MAJOR}
        EXPORT_NAME validator
        OUTPUT_NAME nlohmann_json_validator       <---------
        )
```

Was before the PR,

```
set_target_properties(nlohmann_json_schema_validator
                      PROPERTIES
                          VERSION ${PROJECT_VERSION}
                          SOVERSION 2)
```

**Comment by LecrisUT** [comment]
Oh yes, should have made a discussion issue. Is it breaking any api downstream? If the package is imported via FetchContent or any package manager it should not matter. I think the whole naming convention should be simplified in a later version

**Comment by LecrisUT** [comment]
Uhm, we just changed it back, but please tell us what is your build method? I want to do a naming simplification in #272 and it will be helpful to know what are the current downstream workflow to keep things compatible for a while.

**Comment by EGuesnet** [comment]
Our build method is 
```
cmake \
    -DBUILD_SHARED_LIBS=ON \
    .. \
    && make \
    && make install
```

It is done a build container, we next get libs created, and compile our software with cmake, and a CMakeLists.txt with

```
target_link_libraries(ourLib PUBLIC
    [...]
    nlohmann_json_validator
)
```

**Comment by LecrisUT** [comment]
> It is done a build container, we next get libs created, and compile our software with cmake, and a CMakeLists.txt with
> 
> ```
> target_link_libraries(ourLib PUBLIC
>     [...]
>     nlohmann_json_validator
> )
> ```

Ok, so it is a cmake workflow. It should be independent of the actual library name in that case. Note the few changes in the cmake options recently introduced though.
