### ISSUE TITLE
Build fail on latest MSVC 17.6.2, cl.exe v19.36.32532

### ISSUE THREAD

**Issue by mark-99** [pboettch/json-schema-validator#273]
```vcpkg\buildtrees\json-schema-validator\src\2.2.0-e87f98a2b7.clean\src\json-validator.cpp(606): error C7692: 'bool nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>::operator ==(const nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>> &) noexcept const': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope```

**Comment by VolkerChristian** [comment]
The same error happens on linux using g++-13 (current debian sid).
Did not happen with g++-12 and clang-14 and bevore.

**Comment by mark-99** [comment]
Hi - this still doesn't work, probably because there hasn't been a release since Nov 2022 so vcpkg hasn't picked up any newer versions.

**Comment by mark-99** [comment]
main doesn't seem any better:
```C:\Users\User\source\repos\MdpCpp\vcpkg\buildtrees\json-schema-validator\src\9c3449c157-f7088f3896.clean\src\json-validator.cpp(606): error C7692: 'bool nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>::operator ==(const nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>> &) noexcept const': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
```

**Comment by mark-99** [comment]
Yes msvc looks ok if I use latest main branch.
