### ISSUE TITLE
where can I find libnlohmann_json_schema_validator.so.1?

### ISSUE THREAD

**Issue by yuffon** [pboettch/json-schema-validator#274]
Hi,
I am compiling a project which needs libnlohmann_json_schema_validator.so.1.
I notice that the releases published in this repository only include version 2+.
Where can I find libnlohmann_json_schema_validator.so.1?
Thanks.

**Comment by pboettch** [comment]
It depends on how you build the project where the files are placed. Not really sure how to help you.
