### ISSUE TITLE
Use schema+nlohmann type to determine numeric validation type

### ISSUE THREAD

**Issue by RPGillespie6** [pboettch/json-schema-validator#28]
[Nlohmann currently provides an API](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a2b2d781d7f2a4ee41bc0016e931cadf7.html) that returns one of 3 different numeric types:

```
number (integer) | value_t::number_integer
number (unsigned integer) | value_t::number_unsigned
number (floating-point) | value_t::number_float
```

Consider the following:

```c++
#include <iostream>

using namespace std;

int main() {
  uint64_t x = 99999999999999997;
  uint64_t y = 99999999999999999;
  double a = x;
  double b = y;
  cout << to_string(x == y) << " " << to_string(a == b) << endl;
}
```
In this case the library will falsely validate numbers since there isn't enough fractional bits in the double to distinguish the two numbers.

This library should:

1. Check if the Schema v4 type is `number` vs. `integer`

a. If the Schema specifies `integer`, then it should first check that the provided number is either `value_t::number_integer` or `value_t::number_unsigned`

If not, the validation should fail.

b. When doing the comparison, the type that allows the maximum precision should be chosen.

For example, if the schema type is `integer`, then, `int64_t` or `uint64_t` should be used. If the comparison value and actual value are both `value_t::number_unsigned`, then choose `uint64_t`, otherwise choose `int64_t`.

Otherwise, if schema type is `number`, `double` should be used.

2. Mention in the README Weaknesses section that due to c++ constraints, this library can only validate against 64-bit integers, unsigned integers, or double precision even though the JSON spec has arbitrary precision (i.e. `bignum`)

**Comment by RPGillespie6** [comment]
You may also just want to use native `nlohmann` types so that if nlohmann's library changes, so will yours:

https://github.com/nlohmann/json/blob/develop/include/nlohmann/json_fwd.hpp

```c++
         class NumberIntegerType = std::int64_t,
         class NumberUnsignedType = std::uint64_t,
         class NumberFloatType = double,
```

**Comment by pboettch** [comment]
Yeah, when thinking about this numeric-problem during my offline-afternoon I came to the conclusion that I simply have to base myself of `nlohmann::json` numeric types. Good idea. Thanks for insisting.
