### ISSUE TITLE
exclusiveMaximum and exclusiveMinimum behavior inverted

### ISSUE THREAD

**Issue by RPGillespie6** [pboettch/json-schema-validator#29]
According to JSON Schema spec,

exclusiveMaximum/Minimum is a flag that tells you if the maximum value should be included or not.

This library has 2 bugs:

1. The behavior in `validate_numeric` is inverted (i.e. if exclusiveMaximum is present, it does an inclusive comparison)
2. The value of the flag is not checked.

The correct behavior would be to do something like:

```c++
    const auto &excl = schema.find("exclusiveMaximum");
    bool exclusive = (excl != schema.end()) ? excl.value().get<bool>() : false;
```

And then in the comparison logic:
```c++
    if (exclusive)
        return value > max; //exclusive comparison
    else
        return value >= max; //inclusive comparison
```

This is assuming you have a type-independent comparison utility:

```c++
//uses the types the nlohmann uses under the hood instead of constricting to double
bool violates_numeric_maximum(const json &max, const json &value, bool exclusive)
{
    if (exclusive)
        return value > max;
    else
        return value >= max;
}
```

I can prepare a PR

**Comment by pboettch** [comment]
Please do a PR. :+1:

The scary thing is that the JSON-Schema-Test-suite succeeds the exclusive Min/Max-tests. Because of the impression of double. (it compares 1.1 and 1.1). Double seems not to be able to represent that value exactly.

**Comment by pboettch** [comment]
I was wrong. There is currently no bug in this library. But I agree the folded logic (violate vs. exclusive vs. accept) makes it hard to understand.

**Comment by pboettch** [comment]
If you agree, please close this bug.

**Comment by RPGillespie6** [comment]
Ah, my mistake. You are correct.

In that case the only bug was that the library was previously not examining the boolean value of "exclusiveMaximum" as far as I could tell.

**Comment by pboettch** [comment]
I already closed this issue via a commit-message (which has disappeared in the meantime). Please feel free to comment the last commit and create new PR for anything you'd like.
