### ISSUE TITLE
`multipleOf` fails on double-value

### ISSUE THREAD

**Issue by dhmemi** [pboettch/json-schema-validator#293]
```cpp
void test () {
  nlohmann::json schema = {{"type", "number"}, {"multipleOf", 0.001}};
  nlohmann::json data = 0.3 - 0.2; // 

  const nlohmann::json_schema::json_validator validator(schema);
  validator.validate(data);
} 
```

This simple test case will throw an error due to floating point computational error:

```
At  of 0.09999999999999998 - instance is not a multiple of 0.001000
```

Although, strictly speaking, this is not a bug. But it makes the `multipleOf` validation for floating-point numbers completely unusable in real-world usage scenarios. 

Is there any suggestions on how to solve this problem?

**Comment by pboettch** [comment]
Sadly this is nothing related to this library but rather a C/C++ datatype issue.

We are already using  

```C++
	bool violates_multiple_of(T x) const
	{
		double res = std::remainder(x, multipleOf_.second);
		double eps = std::nextafter(x, 0) - static_cast<double>(x);
		return std::fabs(res) > std::fabs(eps);
	}
```

to minimize floating point derivation. Seems not to be enough in your case.

Actually it is strange. Is this maybe a platform-bug? Are you x86?

**Comment by pboettch** [comment]
If you could create a PR with this change and adding your case (and other) with a test, I think this can be integrated here.

**Comment by pboettch** [comment]
maybe limiting it to T = double.
