### ISSUE TITLE
Unable to compile with preinstalled nlohmann json library

### ISSUE THREAD

**Issue by elnoir** [pboettch/json-schema-validator#313]
My build environment is the folowing:
- Windows, Visual Studio 2019 - 64 bit
- nlohmann::json library (version: 3.11.2) compiled as a single header and installed with CMake 

Reprosteps:
```
cd json_validator.git
mkdir build
cd build
cmake -S .. -B . -G "Visual Studio 16 2019" -Dnlohmann_json_DIR:PATH="../where/the/library/was/installed/nlohmann/share/cmake/nlohmann_json/"
cmake --build .
```

Result:
```
C:\work\git\json_validator.git\src\json-validator.cpp(878,1): error C2440: 'initializing': cannot convert from 'const nlohmann::json_abi_v3_11_2::json' to 'T' [C:\work\git\json_validator.git\build\nlohmann_json_schema_validator.vcxproj]
C:\work\git\json_validator.git\src\json-patch.cpp(68,14): error C3688: invalid literal suffix '_json'; literal operator or literal operator template 'operator ""_json' not found [C:\work\git\json_validator.git\build\nlohmann_json_schema_validator.vcxproj]
```
The first issue seems in incorrect casting: I beleive it should be
```
T value = instance.get<T>();
```
The second error seems to be regarding the move of the json literal:[see here](https://json.nlohmann.me/api/operator_literal_json/)
The following code did the trick.
```
using namespace nlohmann::literals;
```
After this modification the library compiles, but most of test cases are still broken due to the missing literals.

**Comment by elnoir** [comment]
Okay, it seems it was an issue with the installation of the `nlohmann json` library. It was built from the develop branch instead of the version tag.

**Comment by LecrisUT** [comment]
Thanks, that's also useful to know that it will have to be addressed for the future version
