### ISSUE TITLE
CMake install target does not install dll on windows

### ISSUE THREAD

**Issue by bvstrien** [pboettch/json-schema-validator#314]
Since version 2.3.0 (commit https://github.com/pboettch/json-schema-validator/commit/0d60d48a586965b56d1f5c89a1e7a5cedbbdb8f2) the install target on windows is broken, as predicted by the following comment:

https://github.com/pboettch/json-schema-validator/blob/349cba9f7e3cb423bbc1811bdd9f6770f520b468/src/CMakeLists.txt#L58

The problem seems to be the use of the non-existent `${CMAKE_INSTALL_RUNTIMEDIR}`, replacing it with `${CMAKE_INSTALL_BINDIR}` fixed it for me. The documentation for [install(TARGETS)](https://cmake.org/cmake/help/latest/command/install.html#targets) also suggests `RUNTIME` should be set to `${CMAKE_INSTALL_BINDIR}`.

I've attached a patch, applying this fix.
[fix_cmake.patch](https://github.com/pboettch/json-schema-validator/files/14100814/fix_cmake.patch)

**Comment by pboettch** [comment]
Could you create a PR instead of adding a patch to this issue?

**Comment by pboettch** [comment]
@LecrisUT What do you think?

**Comment by LecrisUT** [comment]
I haven't seen any good windows CMake scripts that I can reference and I am not familiar enough with the ecosystem. Maybe there it does make sense to have cpack and stuff.

Anyway regarding `CMAKE_INSTALL_RUNTIMEDIR` -> `CMAKE_INSTALL_BINDIR`. Indeed the former does not exist. The latter expands to `bin`, is that an appropriate design on windows or should it be `lib`. If you have any reference @bvstrien it would be greatly appreciated

**Comment by bvstrien** [comment]
I don't have a direct reference. But I consume this library via vcpkg, and microsoft provides clear guidance there: [Installation directory layout conventions](https://learn.microsoft.com/en-us/vcpkg/reference/installation-tree-layout)

In short, the bin dir should contain the dll files, as they should be next to the exe files, and the lib dir should contain static libraries and import libraries. That now seems to be the case again, and vcpkg installs it properly after the fix.

**Comment by bvstrien** [comment]
I'm not quite sure what you're asking, but it basically automates downloading, building and deploying the packages using the library-provided build tools. See their "portfile" [here](https://github.com/microsoft/vcpkg/blob/7dc284a6ad0b9cb8ccd618c8dc78c360fbd93b83/ports/json-schema-validator/portfile.cmake), which calls `vcpkg_cmake_install()`, which presumably just ends up calling `cmake --install`.

**Comment by LecrisUT** [comment]
Thanks, you've answered my question :D. Yeah you need to upload some metadata similar to homebrew and other packages. Cheers for the assist @bvstrien
