### ISSUE TITLE
additionalProperties isnt working

### ISSUE THREAD

**Issue by markusheimerl** [pboettch/json-schema-validator#325]
```
    json schmemavalidatenamsepace::schema = R"(
    {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
            "asd": {
                "type": "array",
                "items": {
                    "type": "string",
                    "pattern": "^[1-9]\\d*:[..."
                }
            }
        },
        "additionalProperties": false
    }
    )"_json;
```

https://www.learnjsonschema.com/2020-12/applicator/additionalproperties/

This should disallow any property that is not "asd", but I cannot confirm that it does.

**Comment by pboettch** [comment]
Could you create a complete test which shows that additionalProperties does not work?

**Comment by markusheimerl** [comment]
Thank you for taking the time to check the schema validator. I'll check my side on Monday again. I cannot directly share the code where I am experiencing the issue in, so I'll have to try to replicate it in a toy example.

**Comment by pboettch** [comment]
Do not hesitate to reopen this one, or maybe a new one with the real error you've discovered. (I double that additionalProperties is the one).
