### ISSUE TITLE
Format checker is not working in v2

### ISSUE THREAD

**Issue by mabondarenko** [pboettch/json-schema-validator#44]
Hi, 
i'm using `v2` commit `aa3715b`.

I create a validator object and pass it the format check function like shown in example app.
And my scheme haves a property:
``` 
  {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "properties": {
                 "end_time": {
                      "type": "string",
                      "format": "date-time",
                      "maxLength": 19,
                      "example": "2018-09-19 23:59:59"
                  }
...
```
when I perform validation I get an error:
```
path='': '"2018-09-12 19:00:00"'
A format checker was not provided but a format-attribute for this string is present.  cannot be validated for date-time
```
why it happens? Why doesn't the `string class` use the parent function but haves own format checker pointer that always nullptr and nowhere assigins the value?
```
class string : public schema
{
...
    std::function<void(const std::string &, const std::string &)> format_check_ = nullptr;
```
I could be wrong, but it seemed to me that the `date-time` is a format supported by the `draft-07/schema` and I do not need to have my own format check... How can i use buit-in formats?

**Comment by pboettch** [comment]
The format-checker is not at all used right now. I thought it was, but didn't test. As usual. Thanks for finding.
