### ISSUE TITLE
Assumption about acceptable compiler flags

### ISSUE THREAD

**Issue by SamJ1** [pboettch/json-schema-validator#53]
In the top-level CMakeLists.txt (around line 63), the compiler flags -Wall -Werror are set when the compiler is not the Visual Studio compiler.  However, there are a number of compilers besides the Visual Studio compiler that do not accept those flags. In particular, the Cray C++ compiler does not and it fails to compile because of those flags.  I seems that it would be better to check for compilers that do accept those flags and only include them under those conditions.

**Comment by pboettch** [comment]
Agreed.

Do not hesitate to suggest a change via a pull-request.
