### ISSUE TITLE
signed number validation

### ISSUE THREAD

**Issue by gzzi** [pboettch/json-schema-validator#54]
Hi,

We try to validate this schema:
```
{
  "type": "object",
  "properties":
  {
    "myint":{
      "type": "integer",
      "minimum": -2 
    }
  }
}
```

on this object:

```
{
  "myint": 0 
}
```

And we get the error: `At /myint of 0 - is below minimum of 18446744073709551614`. We can workaround it by 

```
@@ -996,7 +997,8 @@ std::shared_ptr<schema> type_schema::make(json &schema,
        case json::value_t::null:
                return std::make_shared<null>(schema, root);
        case json::value_t::number_unsigned:
-               return std::make_shared<numeric<json::number_unsigned_t>>(schema, root, kw);
+               return std::make_shared<numeric<json::number_integer_t>>(schema, root, kw);
        case json::value_t::number_integer:
                return std::make_shared<numeric<json::number_integer_t>>(schema, root, kw);
        case json::value_t::number_float:
```

and all test are passing but probably you get issue with big number.

Best regards

**Comment by pboettch** [comment]
This is related to fact that in this library unsigned and integer-types are distinguished, whereas in json-schema they are not. 

The solution would be to tread unsigned-values as integers all the time. However that would limit the unsigned range: As of today using nlohmann's types: 2^63 (signed) vs. 2^64 (unsigned)

**Comment by pboettch** [comment]
It closed this issue, but I'd still like you to test the change. Feel free to get back if this solution is not correctly thought through.

**Comment by gzzi** [comment]
This work fine. Thank you!
