### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by v-miswar** [pboettch/json-schema-validator#6]
Hi,

I'm not great at computering and I'm having some trouble building and using this library.

First I put nlohmanns json.cpp in your src directory.

Then I ran cmake .. -DNLOHMANN_JSON_DIR=".src/json.hpp" it said /wextra was invalid. Wextra is a gcc flag so I just deleted it from cmakelists.txt and it appeared to cmake correctly.

Next I tried to run cmake --build . and I get 

```
"C:\Code\json-schema-validator\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Code\json-schema-validator\build\json-schema-validate.vcxproj" (default target) (3) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'Debug\json-schema-validator.lib' [C:\Code\json-schema-validator\build\json-schema-vali date.vcxproj]
```
What's the issue?

**Comment by pboettch** [comment]
Sorry, I don't know how to run the compilation process on Windows. However I know that at least one user has succeeded in building a .dll of this library with Visual Studio.

**Comment by pboettch** [comment]
I'm closing this issue. Feel free to reopen it, if you still need help.
