### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by cumafo** [pboettch/json-schema-validator#60]
We are using your software for validating big amounts of receipts and are very satisfied.
However, the validation is the bottleneck of our process, and it has to be handled by several threads. Is there any plans/would it be possible parsing the schemas into a read only json_validator to be used in different threads?
Today it is in solved in runtime by using:
        thread_local shared_ptr<json_validator> v = LoadJson();
        assert(v != 0); // we did parse at start so assume ok
But this works only when using one root schema (need to handle multiple versions).
Do you have any other suggestions?
/Curt

**Comment by pboettch** [comment]
Thank you for your nice words. It's always good to hear use cases of users.

Normally json-schema-validation is thread safe by using the same instance over several threads. The validate-method is const, meaning it does not change the object's content during validation.

That said you can just create several validators (one per version) and then use the right one from your threads. No need to copy or to create multiple instances for each thread.

Did you try that already and faced problems?

**Comment by cumafo** [comment]
Thanks for quick response.
I have missed the 'const' in v2, I think it was not in v1.
Perfect.
/C

**Comment by pboettch** [comment]
Close this one?

**Comment by cumafo** [comment]
Yes



Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: Patrick Boettcher <notifications@github.com>
Datum: 2019-06-13 12:10 (GMT+01:00)
Till: pboettch/json-schema-validator <json-schema-validator@noreply.github.com>
Kopia: Curt Lestrup <curt@lestrup.se>, Author <author@noreply.github.com>
Ämne: Re: [pboettch/json-schema-validator] multithreading (#60)


Close this one?
