### ISSUE TITLE
Invalid JSON schema is accepted and successfully validated against

### ISSUE THREAD

**Issue by szotsaki** [pboettch/json-schema-validator#61]
The following JSON schema is invalid:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "test": {
        "N1": {
          "type": "string",
          "minLength": 100
        }
      },
      "additionalProperties": false,
      "required": [
        "N1"
      ]
    }
  },
  "uniqueItems": true,
  "additionalProperties": false
}
```
Problems with it:
* Unnecessary `"test":` inside `properties`
* `additionalProperties` and `required` should be outside of `properties`

The following short JSON successfully validates against it:

```json
[
  {
    "N1": "Too short",
    "NewPropertyWhichIsInvalid": 5
  } 
]
```

(Tested with the validator app.)

**Comment by pboettch** [comment]
Unfortunately the schema you assume to be invalid is valid. It does not work as you expected but it is not invalid. 

Check with the json-schema spec for more details, but basically:

> Unnecessary "test": inside properties

Unnecessary yes, but not invalid. `test` is the property of this object-schema. It contains a schema which is an object. This object contains an unknown field `N1` which is ignored by the validator (unless it is explicitly referenced).

> additionalProperties and required should be outside of properties

Yes. As you wrote it, `additionalProperties` is seen as a property of your items-object-schema. 

JSON-schema is permissive. It does not warn or prevent you from doing mistakes like this.

Unrelated to this library, I'll close.
