### ISSUE TITLE
Extra parameter validation is not handled by library

### ISSUE THREAD

**Issue by ravi3535** [pboettch/json-schema-validator#62]
Additional parameter in JSON is not validated properly.

**Comment by ravi3535** [comment]
Below is my schema,

{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "A person",
    "properties": {
        "name": {
            "description": "Name",
            "type": "string"
        },
        "age": {
            "description": "Age of the person",
            "type": "number",
            "minimum": 2,
            "maximum": 200
        }
    },
    "required": [
                 "name",
                 "age"
                 ],
    "type": "object"
}

Input json (Note: temp field is added)
{
"name": "Albert",
"age" :42,
"temp": 20
}
Expected output : Invalid JSON with one additional parameter error
Actual Output - success (i.e. document is valid  )

**Comment by ravi3535** [comment]
It is possible using "additionalProperties": false field in schema, below is modified json schema,

{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "A person",
    "properties": {
        "name": {
            "description": "Name",
            "type": "string"
        },
        "age": {
            "description": "Age of the person",
            "type": "number",
            "minimum": 2,
            "maximum": 200
        }
    },
    **"additionalProperties": false,**
    "required": [
                 "name",
                 "age"
                 ],
    "type": "object"
}

**Comment by pboettch** [comment]
Yes, by default additionalProperties is an empty schema, which results in "always-true" evaluation.
