### ISSUE TITLE
Can a line and column number be added to the error message?

### ISSUE THREAD

**Issue by mjcrawford22** [pboettch/json-schema-validator#68]
We will be using this to validate our input files as well as intra-process communications. Some input files will be hundreds of lines long. Is it possible to add add the line and position number of the anomaly? E.g., "ERROR: ..., error at line 40, column 17".

**Comment by pboettch** [comment]
That's a hard thing to do. I'm not aware of that the underlying `nlohmann::json` provides file-location information for its fields. If this is true we won't be able to tell you where invalid field is located.

**Comment by pboettch** [comment]
The underlaying JSON-library doesn ot support source-references. So it can be done here.
