### ISSUE TITLE
multiple calls of set_root_schema issue

### ISSUE THREAD

**Issue by ArkadiuszRaj** [pboettch/json-schema-validator#70]
I have a test case when I check if schema regex definition correctly catches proper & not proper settings for folder or script names. 

But it seems that set_root_schema() does not delete previous content thus reading the same schema json second time throws exception.

```
[==========] Running 20 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 20 tests from ConfigTest
[ RUN      ] ConfigTest.initialization
[       OK ] ConfigTest.initialization (743 ms)
[ RUN      ] ConfigTest.verify_schema
[       OK ] ConfigTest.verify_schema (742 ms)
[ RUN      ] ConfigTest.verify_defaults
[       OK ] ConfigTest.verify_defaults (746 ms)
[ RUN      ] ConfigTest.verify_regex_folder_p
unknown file: Failure
C++ exception with description "schema with  # /properties/ASTROMETRY/properties/CONSTRAINT/properties/AREA/properties/MAX already inserted" thrown in the test body.
[  FAILED  ] ConfigTest.verify_regex_folder_p (18 ms)
```

Excerpt from my code:
```
using json_validator = nlohmann::json_schema::json_validator;

class Configuration {
private:
    void init_();

    static json_validator validator;

    static json configuration_schema;
    static json system_configuration;
public:
    Configuration(bool reload = false)
    {
        if(reload || !ready()) init_();
    };

    bool ready()
    {
        return configuration_schema.size() > 0;
    }

[cut]..[/cut]

};

json Configuration::configuration_schema;
json Configuration::system_configuration;
json_validator Configuration::validator;

void Configuration::init_()
{
  configuration_schema = json::parse(CONFIGURATION_SCHEMA);
  validator.set_root_schema(configuration_schema);
  system_configuration = json::parse(CONFIGURATION_DEFAULTS);
}
```
When new Configuration object is created with reload option set to true, exception from validator is raised. Of course I can secure configuration_schema & validator to be initialised  only once, but in my opinion set_root_schema shall allow multiple initialisations.

I am using schema validator code tagged with 2.0.0

**Comment by pboettch** [comment]
Hmm, interesting point. It seems the API of the validation is not coherent. `set_root_schema()` was meant to be called once per validator-instance. To force this behavior it should actually be an argument to the constructor.

On the other hand, why not allowing to call set_root_schema multiple times. Let me think about it a bit.

However, in your case there is no reason to set the root-schema again. It is a waste of resources (as the schema's JSON is identical, right?) and should be done once. 

Maybe we can add a constructor which allows to set the root-schema at construction time, then you can call this constructor of your static variable:

```C
json_validator Configuration::validator(json::parse(CONFIGURATION_SCHEMA));
```

What do you think?

**Comment by ArkadiuszRaj** [comment]
Hi, Yes that is something I did to speedup tests (not reloading static data multiple times).
However maybe I was misled by this line: https://github.com/pboettch/json-schema-validator/blob/e14d2896ff952f731c094ddd69af0ef072d15861/src/json-validator.cpp#L174

Shouldn't that remove content of schema?

**Comment by ArkadiuszRaj** [comment]
Thanks!
With this constructor the code of validator would be in my opinion more consistent with original Niels Lohmann implementation.

```
json Configuration::configuration_schema = json::parse(CONFIGURATION_SCHEMA);
json_validator Configuration::validator;//(json::parse(CONFIGURATION_SCHEMA));
```

Above code is compiling well, but I would like to remove comment :)

**Comment by ArkadiuszRaj** [comment]
Actually I need it as one option of the app I create is to dump both schema
and current configuration.

pon., 14 paź 2019 o 11:43 Patrick Boettcher <notifications@github.com>
napisał(a):
