### ISSUE TITLE
Support Draft 2019-09

### ISSUE THREAD

**Issue by mortymacs** [pboettch/json-schema-validator#74]
Hi :)
Is there any plan that exists to support the latest Draft? (Draft 2019-09)
I'd like to contribute.

**Comment by pboettch** [comment]
No plan. 

I haven't looked at the spec yet. It took some time to release it. Will they do a new iteration within the 6 months period?

The biggest difficulty when writing the validator for me, was to get the location/$ref-stuff working correctly. The rest is easy - if the implementation sticks to the spec's guidelines.

**Comment by pboettch** [comment]
I just flew over the spec. annotations, recursiveRefs, I'd need some time to swallow this.

Then there is the validation output @garethsb-sony already took a look at and started something in #67 .

It seem that this release of the spec is no more a draft. It might be worth to do the efforts quickly.

Ideally we could split up the work. But I'm not yet able to create independent work-items.

**Comment by mortezaipo** [comment]
Great! then if I can do anything please let me know ;)

**Comment by pboettch** [comment]
Let's go for 2020-12 #153 if anything.
