### ISSUE TITLE
reference validation miss its pointer part when using custom schema loader

### ISSUE THREAD

**Issue by alsauve** [pboettch/json-schema-validator#75]
Hi there

## brief
I'm currently stuck with reference validation while implementing a custom loader.
The loader itself is correctly called when loading schema but validation fails 
in a way like the $ref pointer fragment is missing

This issue seem related with #50 but in my case the external schema are loaded correctly

## description
The loader callback implements this signature
  //typedef std::function<void(const json_uri & /*id*/, json & /*value*/)> schema_loader;

  And fill "value" with the schema referenced by "id" with this code:  
  `value = getSchema(location);`

* Validating a schema with no $ref is just fine 
* but when moving the definition in a second external schema file validation fails with:
    ` At /0 of "INT" - unresolved schema-reference /TypeId.json # /data/TypeId`

## Files hierarchy

* **Validated data**  : 
ok_list = R"(["INT", "LONG"])"_json;

* **root schema**
{      "type" : "array",
        "items": { "$ref":"TypeId.json#/data/TypeId"} } 

* **TypeId.json**
{ "data" : {
    "TypeId" : {
        "type"        : "string",
        "description" : "POD type of data matching bmf::data::TypeId enum", 
        "enum" : [ 
            "CHAR", "UCHAR", "SHORT", "USHORT", "INT", "UINT",
            "LONG", "ULONG", "FLOAT", "DOUBLE" ]    }  }  }

## First debug attempt
I'm using gdb and the "print hello" method, here are some bits of output from the second one: 
```
type_schema::validate ptr="" instance=["INT","LONG"]
array::validate ptr=""
array::validate ptr/index="/0"
array::validate i="INT"
schema_ref::validate ptr="/0"
schema_ref::validate target=0
```

Finally an exception is thrown at `schema_ref::validate` which target is curiously empty???

I would expect that target would contain the *fragment* of schema pointed by
the  uri in: `/data/TypeId` but this is not the case. 

Any clues to fix this issue?

**Comment by alsauve** [comment]
### Solution
Finally found that this issue is related to a requirement of *Json-schema-validator* that
 references are pointing inside a "/definition" location. 
My $ref has become `"$ref":"TypeId.json#/definitions/TypeId"` And now everything is working fine.

### Caveat
The "definitions" location is indicated as 
* *customary*  by the JSON standard draft 7
* *but not required*. 

See:
    https://json-schema.org/understanding-json-schema/structuring.html

### Proposal
Would it be OK to relax this requirement in order to get a smoother end user experience?

**Comment by pboettch** [comment]
Nice report, I'll take a look and will check the standard, iirc your first approach should be ok.

**Comment by pboettch** [comment]
The draft-7 says about "unknown keywords":

> 4.3.1.  JSON Schema Values and Keywords
> [..]
> A JSON Schema MAY contain properties which are not schema keywords.
> Unknown keywords SHOULD be ignored.

But, this library supports unknown keywords in the sense that they interpreted as a schema if they are referenced by some `$ref`. Your initial case should work.

**Comment by pboettch** [comment]
I can already confirm that your initial code should have worked, but doesn't because there is a bug.
