### ISSUE TITLE
No regex support for gcc 4.8.5

### ISSUE THREAD

**Issue by mrspacemankey** [pboettch/json-schema-validator#76]
Hello,

First of all, thank you for making your project open-source on github.

### Brief

I am limited to use gcc 4.8.5 with my current project, and also can not use boost. Which means I am unable to use any standard regex implementation. In theory this project supports this case by defining `NO_STD_REGEX` in `json-validator.cpp`.

### Problem

However, compilation fails as `patternProperties_` is not defined in this case in `json-validator.cpp:789`.

### Solution

This can be easily fixed by adding `#ifndef NO_STD_REGEX`, `#endif` around the lines 789-793.

Thank you for considering patching this compile error for the unfortunate souls bound by corporate IT.

**Comment by pboettch** [comment]
Why don't you do a pull-request with these changes? Would be very nice.
