### ISSUE TITLE
override system nlohmann/json.hpp

### ISSUE THREAD

**Issue by bgodard** [pboettch/json-schema-validator#78]
I have an old version of nlohmann json on my linux system in the default search path.
I want to build against a recent version of nlohmann json in my home directory. However cmake is ignoring the option: 
`-Dnlohmann_json_DIR=/home/...`

and using the default path: /usr/include/nlohmann/json.hpp
via /usr/lib64/cmake/nlohmann_json/ :
`-- Found nlohmann_json-cmake-package - linking with it`

which results in a compilation failure:
`error: #error "Please use this library with NLohmann's JSON version 3.6.0 or higher"`

Is there a way I can tell cmake to ignore the default path via command line argument, without editing CMakeLists.txt?

**Comment by pboettch** [comment]
I took a look and reproduced your issue.

The way to find json.hpp in this project during cmake-configuration-time is quite complex already. I'm not sure whether adding another boolean-variable to force CMake looks for json.hpp in the given path will improve the situation. It won't making it more complex and add error possibilities.

Maybe one question could be: why is there a json.hpp installed in the system and you don't want to use it? Remove it, or update it.

I mean, other components of your project would need to work the same way as this library. Using different versions of json.hpp in one project might not be good idea.

**Comment by bgodard** [comment]
Thank you for your reply.

I do not have admin privilege on that system. Nevertheless I have found a way around by adding a top level CMake script in my project build system that builds together nlohmann json and json-schema-validator as subprojects.
```cmake
set(JSON_BuildTests OFF CACHE INTERNAL "")
add_subdirectory(${PROJECT_SOURCE_DIR}/ext/json/nlohmann)
set(COPY_BUILD_TESTS ${BUILD_TESTS} BOOL)
option(BUILD_TESTS OFF)
set(BUILD_SHARED_LIBS ON)
add_subdirectory(${PROJECT_SOURCE_DIR}/ext/json/schema)
if (COPY_BUILD_TESTS)
   option(BUILD_TESTS ON)
endif()
```
Thank you again. You can close the issue if you want.

**Comment by pboettch** [comment]
OK, so this is a work-around: building both projects as submodule.

Too bad that in another issue I learnt that there are inconveniences as well.
