### ISSUE TITLE
CMake Error because of install(EXPORT ...) maybe turn into an option?

### ISSUE THREAD

**Issue by merlinmarek** [pboettch/json-schema-validator#79]
Hey there.
I have both, the validator and nlohmann_json as git submodules in my project. I build a binary that does not export nlohmann_json and the validator. When I want to generate the build files with CMAKE, I get the following error

`
-- Using the single-header code from /tmp/tmp.ksoqdZpHuy/nlohmann_json/single_include/
-- Found nlohmann_json::nlohmann_json-target - linking with it
-- Configuring done
CMake Error: install(EXPORT "nlohmann_json_schema_validatorTargets" ...) includes target "nlohmann_json_schema_validator" which requires target "nlohmann_json" that is not in any export set.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
`

If I comment out the lines
`
install(EXPORT ${PROJECT_NAME}Targets
        FILE ${PROJECT_NAME}Targets.cmake
        DESTINATION "${INSTALL_CMAKE_DIR}")
`
at the very bottom of the CMakeLists.txt, I do not get the error and the build file generation succeeds. I am not a CMake expert, so maybe there is a better way to get around this.

I have prepared a dummy project that is setup the same way as my current real project [here](https://github.com/merlinmarek/json_schema_validator_issue).

How do you think about adding an option for the export (and maybe related functionality)?

**Comment by pboettch** [comment]
Hmm, I'll take a look soon, I'm in the same situation for a project I haven't updated yet.

**Comment by pboettch** [comment]
I found a solution, which is deactivating entirely the install-commands when being used as a submodule.

All these different ways of how to build the library is making harder and harder. Letting some time goes by I'm sure reducing the possibilities and forcing users into 2 or max 3 possibilities.

Instead of using add_subdirectory(), which pollutes a little bit your project, in the past I chose to use ExternalProject for including the validator lib.

**Comment by merlinmarek** [comment]
#81 is exactly what I was looking for. Will this be merged?
I tried to setup the dependency using ExternalProjectAdd, but I am running into issues. I would prefer the add_subdirectory way, but out of curiosity, could you provide a minimal ExternalProjectAdd example?
I am using this:
`
ExternalProject_Add(json_schema_validator
	SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/json_schema_validator"
	CMAKE_CACHE_ARGS
	-DBUILD_TESTS:BOOL=OFF
	-DBUILD_EXAMPLES:BOOL=OFF
	-Dnlohmann_json_DIR:PATH=${CMAKE_CURRENT_SOURCE_DIR}/nlohmann_json/include/
)
`
which tries to install the validator when building (which is not what I want) and fails with:
`
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/home/user/projects/foo/build/json_schema_validator-prefix/src/json_schema_validator-build/libnlohmann_json_schema_validator.a"
  to "/usr/local/lib/libnlohmann_json_schema_validator.a": Permission denied.
`

**Comment by pboettch** [comment]
When using `ExternalProject_Add` you need to create the correct dependencies and import the libraries which are created by the external-project:

```CMake
ExternalProject_Add(project-ext
    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/
    CMAKE_ARGS
        -DBUILD_SHARED_LIBS=OFF
        -DBUILD_TESTING=OFF
    BUILD_BYPRODUCTS
        <BINARY_DIR>/libABC.a # or .so 
    INSTALL_COMMAND ""
    BUILD_ALWAYS ON)

ExternalProject_Get_Property(project-ext BINARY_DIR)

add_library(project INTERFACE)
target_include_directories(project
    INTERFACE
        source/include ...)
target_link_libraries(project
    INTERFACE
        ${BINARY_DIR}/libABC.a)

add_dependencies(project project-ext)
```
