### ISSUE TITLE
validator does not return all errors

### ISSUE THREAD

**Issue by matsbror** [pboettch/json-schema-validator#8]
Great work,

However, the validator throws an exception on the first error it encounters and any other errors are not caught until you corrected the first. Is there a way to continue validation and return all found errors?

**Comment by pboettch** [comment]
Thanks. You are not the first requesting this feature.

How should the validator report the errors in this case? A list of errors and no more exceptions at all? Or an iterative approach yielding the next error when calling again validate?

**Comment by matsbror** [comment]
I have used valijson before (which doesn't work with the latest nlohman::json, I have heard) and it returns a rather complicated error structure which you need to traverse iteratively. It works, but I would prefer something less complicated. 

You could maybe make use of an optional as return value which contains an error list if there are errors, and not when it worked?

**Comment by pboettch** [comment]
The new version allows you to overload an error-handler-object and pass it to the validation-function. You will be called for each error seen during validation. It will be up to you to decide whether to ignore it or to count or to throw.
