### ISSUE TITLE
Configuraion related issue

### ISSUE THREAD

**Issue by PradumnErwin** [pboettch/json-schema-validator#92]
while executing cmake ../, it is poping-up error (error message is given below ) 
CMake Error: 
  could not find nlohmann/json.hpp or any related cmake-target.  Please set
  nlohmann_json_DIR.

![image](https://user-images.githubusercontent.com/59471345/76925529-ca683e80-68ff-11ea-9503-cdbce7c70713.png)

**Comment by pboettch** [comment]
Did you consult the README-file?

**Comment by pboettch** [comment]
I'm closing this as the README clearly states what to do about, it.
