### ISSUE TITLE
Logging caught exceptions from get_or_create_ref for schemas with $ref to separate file

### ISSUE THREAD

**Issue by Secumfex** [pboettch/json-schema-validator#98]
I'm using the current `master` with NLohmann JSON v3.7.3 on a MSVC 2017 build.
Using a custom loader, I can successfully locate and load the referenced schema definitions and validate the input. So all appears well 👌 from the functional point of view. Awesome work!

However, whenever a schema that has a `$ref` to a separate file, the Console logs an irritating [`307` `type_error` from the `nlohmann::json` library](https://github.com/nlohmann/json/blob/6c7cde181cc5ff5db565e54a897261980af022f1/include/nlohmann/detail/exceptions.hpp#L234).
The exception message is "cannot use erase() with null".

The call stack shows it stems from a [line in `root_schema::get_or_create_ref` ](https://github.com/pboettch/json-schema-validator/blame/940262ceae42848b8bdab1e07fef4c2385b701c3/src/json-validator.cpp#L183) that attempts to call `nlohmann::json::erase` on the `null`-typed `file.unknown_keywords`.

This is an basic example that resembles my use-case:
```c++
nlohmann::json nlBase = nlohmann::json::parse( "{ \"$id\": \"https://some.domain.com/schema/base.schema.json\", \"$ref\": \"test.schema.json\" }" );
nlohmann::json nlRef = nlohmann::json::parse( "{ \"$id\": \"https://some.domain.com/schema/test.schema.json\",\"type\":\"object\" }" );
nlohmann::json_schema::schema_loader loader = [&nlRef] ( const nlohmann::json_uri& id, nlohmann::json& value )
{
	value = nlRef;
};
nlohmann::json_schema::json_validator validator( loader );
validator.set_root_schema( nlBase ); // this line will log the caught exception
```

This is a most minimal example that already produces the caught exception:
``` c++
nlohmann::json nlBase = nlohmann::json::parse( "{ \"$ref\": \"test.schema.json\" }" );
nlohmann::json_schema::json_validator validator;
validator.set_root_schema( nlBase ); // this line will log the caught exception
```

Could you confirm this is just expected behaviour? Since the code in `get_or_create_ref` is in a `try`-block that catches any exception. But wouldn't it be cleaner to avoid this exception all together?

Might this be related to #75 (specifically https://github.com/pboettch/json-schema-validator/issues/75#issuecomment-557203381)?

**Comment by pboettch** [comment]
Thanks for your report. I think you're right, the exception should not happen. I will check what's wrong with your example.

**Comment by pboettch** [comment]
The try-catch is there, to handle the case where `at(ptr)` does not find the reference. This will often fail actually.

So I have to keep this try catch because there is no other way to check in `nlohmann::json` whether a node reference with a `json_pointer` exists.
